### ISSUE TITLE
Searching by set code of old sets does not work

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#10]
For example, `e:Stronghold` works, but `e:STH` does not.

**Comment by taw** [comment]
Well, we use mci codes so it's `e:sh`. I think we could use multiple codes, but there were some conflicts where we need to decide.

**Comment by fenhl** [comment]
I think it would be much more straightforward to use the official set codes rather than these nonstandard codes.

**Comment by taw** [comment]
The difference is only for very old sets, and from what I could tell mci codes are actually more common than gatherer codes. Even gatherer doesn't really expose its codes on its site.

**Comment by fenhl** [comment]
I have never had to use the mci set codes anywhere before. Even mci itself accepts the official set codes.

And I know some of the official set codes can be a bit unintuitive, but most of the conflicts have been solved at this point and MTG JSON 4 will use the official set codes.

**Comment by taw** [comment]
Both code systems are now supported. In case of conflict mci system takes precedence, but there aren't any conflicts right now.

**Comment by fenhl** [comment]
With *Commander Anthology* releasing this week and introducing a conflict, this issue should be revisited. I like that the project has been moving away from magiccards.info idiosyncrasies like the color confusion, and in my opinion this feature should follow.

**Comment by taw** [comment]
CMA/CM1 not works as on Gatherer and indexer now automatically checks any future set code conflicts, so this shouldn't be a problem.
