### ISSUE TITLE
Arena-only cards

### ISSUE THREAD

**Issue by taw** [taw/magic-search-engine#100]
[So it has come to this](https://s3.amazonaws.com/duxsite-mtgarena/c50a7fd7be7f3cbc1e86bc3fe9232150b32efd776cbb87534529ddc213d3e59du46.jpg).

**Comment by fenhl** [comment]
Perhaps this would also be a good time to add support for `game:paper`, `game:mtgo`, and `game:arena`. Each of these queries shows the printings that have appeared in that version of the game.

**Comment by taw** [comment]
I'm totally for it `game:`, but that data should be in mtgjson or indexer.

Right now (IIRC):

* we have no cards which are not on paper
* there are digital-only (=MTGO-only) printings, and we mark them, so `-is:digital` is `game:paper`
* we have no indicators for paper-only vs paper-and-MTGO sets
* many individual cards from paper-only sets (like old sets, Conspiracy, Commander series etc.) get released in treasure chests, which change a lot, so that's a lot of data to track
* Arena started simple enough, but it already turned into this.
* even more annoyingly there are supposedly part of Arena Standard
* there's separate issue of Chinese Standard, which is probably best ignored for now, but if that becomes a habit it could be bad

It's all a mess. Gatherer doesn't even try.

**Comment by silasary** [comment]
it is something we're planning for mtgjson v4

**Comment by taw** [comment]
So, mtgjson v4 has `is:digital`, which can be either MTGO or Arena.

Probably worth asking @ZeldaZach about it - could mtgjson have per-set flag like `isPaper` / `isMtgo` / `isArena` ? (or `isShandalar` lol)

**Comment by taw** [comment]
[It's all now working](https://mtg.wtf/card?q=game%3Aarena+-game%3Apaper).

Still no Shandalar.
