### ISSUE TITLE
Sealed Support

### ISSUE THREAD

**Issue by taw** [taw/magic-search-engine#106]
I'm just redoing https://github.com/taw/magic-search-engine/issues/82 as it got really enormous.

Add support for remaining sets:

- [x] Conspiracy: Take the Crown
- [x] Unstable
- [x] Battlebond
- [x] Guilds of Ravnica

Fix remaining issues (from old ticket):

- [x] support Unstable (contraptions, alt art)
- [x] support any known variation from printed rarities, like Unstable variants (each of N-way variants appears only 1/N as often; presumably Brothers Yamazaki and other alt arts would work the same way)
- [x] add web frontend for it, obviously (this will overlap with whichever solution we have for precons, user-uploaded decks etc.)
- [ ] maybe move more of the calculations to indexer, to make it easier for custom magic sets
- [x] link from set page to Sealed
- [x] is:foil / is:nonfoil - sort of incidental, but Sealed simulator forces getting this information, so might as well expose it. A card can match both (like M10 Lightning Bolt is available both foil and nonfoil, as is vast majority of cards), so these names are a it awkward
- [x] to quote Maro about packs: *To match our collation, there must be at least one common of every color. Also, don't make more than five cards of the same color combination. (You can't have more than five mono-green cards or five blue-red cards.) The one exception is colorless cards if you have chosen a set that has a high as-fan of colorless cards."*

Fix remaining issues (from comments):
- [ ] Unlike Wastes, old cards with multiple images like Brothers Yamazaki or High Tide (FEM) appear at the same total rarity as other cards, i.e. each individual version appears less often.
- [x]  CN2 has a special slot for conspiracies. Other draft-matters cards appear within the normal rarity-based slots.
- [x] I'm totally guessing how foils work. I'm assuming 1/4 of packs contain a foil, it always replaces common slot, all cards from set get to be foiled (including DFCs, Timeshifted cards, basics for sets which don't otherwise put them there, conspiracies, and all the other weirdness), and some ratios between them that shouldn't be totally crazy. I don't like it, but I don't know we can do any better. Someone should at least check my assumptions and numbers if there's anything crazy there.
- [x]  I have no idea how basics were included in old sets. From certain point of view they get own sheet, but what about before? I know for alpha they were printed on all rarity sheets, but that was just a one off as far as I can tell. I assume they were by default printed on common sheet and basically worked as commons. Is that correct, or even sensible? The only set I know for which it's explicitly said its boosters didn't contain basics (but they were in fat packs etc.) was Fate Reforged. There's claims that sets had land sheet as far back as Ice Age, but then only Shards of Alara got dedicated basic slot, so wtf seriously.
- [x]  as intersection of these issues, foil basics.
- [x] add some query for full art lands

Fix remaining issues (from wiki):

- [x] cn2: *Exactly one card every pack is a Conspiracy, replacing the basic land. Other drafts-matters cards take the space of their printed rarity. Because of the alternate art foil version Kaya, Ghost Assassin, collectors view this as a 222 card set, while its presented as a 221 card set.*
- [x] ust *Contraptions are on their own sheet. While the set is presented as a 216-ish card set, six commons each have four variants, one common has five variants, four uncommons and three rares each have six variants. Because of this, collectors view this as a 273 card set.*
- [x] *Prior to Time Spiral, if a booster pack contained a foil card it would replace the card normally found in that rarity. (i.e. the card Shared Triumph is rare, if there was a foil version in a pack it would replace the card found in the rare slot). Starting with Time Spiral, in every set a foil card replaces a common card regardless of the rarity of the foil card.*
- [x] *The Alara Premium Foil Booster pack contained fifteen foil, black-bordered cards from Shards of Alara, Conflux, and Alara Reborn.*
- [x] *core19 - It's because some are replaced with taplands, so there's a bit of mana fixing value in that slot. It's because like 1 in 3 basics are replaced with the tap lands, and 1 in 15 basics is replaced with the Bolas check-card.*

And also:

- [ ] think a bit more if current Dominaria legendary logic is correct
- [ ] make startup performance not horrible
- [x] add another way to compose packs (A = B + C; in addition to A = B or C) to support Battlebond, and make complicated packs simpler

It feels like it's 80% done, so it will take only a bit extra push to get it to MVP level.

**Comment by taw** [comment]
[Here's description of BBD system](https://twitter.com/gavinverhey/status/999437368493948928?lang=en-gb).

**Comment by fenhl** [comment]
GRN has [Gates in the basic land slot](https://clips.twitch.tv/SpinelessFreezingYogurtPraiseIt). The way this question was answered (24 Guildgates per draft) implies that:

1. There are no basic lands in boosters at all (only in Bundles)
2. Guildgates only appear in the basic land slot, not in common slots
3. Gateway Plaza is a Gate but not a Guildgate so it's treated as a regular common

**Comment by taw** [comment]
From wiki:

>  The 5 basic lands of this set are not included within the 259 cards, meaning that they won't appear in booster packs but only in the planeswalker decks and the Bundle.[8] They're all autumnal versions of the Richard Wright basics from Ravnica: City of Guilds and are numbered from #260/259 to #264/259. Neither contained in boosters are the 8 additional planeswalker deck exclusive cards - numbered #265/259 to #272/259 - and the Buy-a-Box promo, which has the number #273/259. Each Guildgate is featured in two common slots, each with different art, much like Wastes in Oath of the Gatewatch.[9]

**Comment by taw** [comment]
Basics only replacing 11th common since Alara block should be modeled already, unless I missed something.

I don't think GDS3 rules are actually collation rules, based on sheets we have. They're roughly the guidelines they use for collation, but also to make challenge better.

**Comment by fenhl** [comment]
I just tested this by generating a bunch of RAV packs and the resulting pool has a lot of nonfoil basics which shouldn't be there.

**Comment by taw** [comment]
So BBD. I can't find any definite sources on what's in boosters.

Just based on what WotC typically does, I'm guessing booster will contain one of: 

* 10 commons
* 9 commons + 1 foil
* 8 commons + 2 matching partner foils

Plus one of:

* 3 uncommons + 1 rare/mythic
* 1 uncommon + 2 matching partner uncommons + 1 rare/mythic 
* 2 uncommons + 2 matching partner rare/mythics

Plus 1 basic. And token/ad card we don't care about.

Does it sound right?

**Comment by taw** [comment]
UST I can just half-ass and treat every variant as separate card. It won't be accurate, but we already have this issue for some old sets.

**Comment by taw** [comment]
[This is interesting claim](https://twitter.com/maro254/status/938830320094216192)

> No, they drop at the exact same rate as a normal set, the same as a common. The difference is Unstable only has one of each basic land while most sets have four. 

So basically saying that foil basics and foil commons should have same rarity.

(this isn't true of regular basics and regular commons)

**Comment by silasary** [comment]
Battlebond collation is explained here:
https://twitter.com/GavinVerhey/status/999437362357649408

>

**Comment by taw** [comment]
> 6. If you open a foil partners, they replace one common and one uncommon. So if you open up a foil partner pair, your pack will still have 2 non-partner uncommons.

So that's one I got wrong. It will be mess to implement, but then again we're just 3 sets away from having Sealed for everything.

**Comment by taw** [comment]
Commons are now color-balanced (for most sets, at least one for each color is guaranteed each pack).

Also, [some claims about common sheet](https://imgur.com/a/E3LQyVs).

**Comment by taw** [comment]
[So here's an interesting claim that Arena doesn't bother with such simulations](https://www.reddit.com/r/magicTCG/comments/bhby3j/psa_war_boosters_bought_or_won_on_mtg_arena_are/).

**Comment by fenhl** [comment]
Arena has two different kinds of packs: “booster” packs (apparently also called “store boosters”, though this is the first time I've seen that term used), which are 5 commons, 2 uncommons and a rare, and “limited” packs, which are the like physical booster packs, except the basic land (if any) is removed.

Booster packs from *Dominaria* don't have the “one legend per pack” rule, and I can confirm that some *War of the Spark* packs have multiple or no planeswalkers. There also doesn't seem to be any guarantee about color distribution in any set. In fact they probably just pick 5 different commons and 2 different uncommons at random. (Rares and wildcards are a bit more complicated, as the pack layout actually depends on your collection and how recently you opened wildcards previously.)

Limited packs seem to be designed to be close to physical booster packs, including the *Dominaria* legendary creature collation and *War of the Spark* planeswalker collation. I don't know how closely they emulate the collation process, though I guess that could be tested using the data from lethe.xyz in one of the two *Ravnica Allegiance* draft formats currently running.

**Comment by taw** [comment]
Battlebond added. Numbers are quite questionable, especially for foil partners. I might be off by 15% on some ratios. It might be worth rechecking it later.

**Comment by taw** [comment]
CN2 and Unstable added. So that's finally all sets. Unstable variants are treated as independent cards, and so overrepresented.

There's a lot of those leftover issues with various unusual sets. With old sets with mechanical booster packing process, it's easy to infer sensible exact rates, as only some mathematically work with sheet sizes.

Nowadays there's this fancy computer controlled booster packing, and ratios get weirder and weirder. DOM, BBD, UST etc. are probably off by a good bit.

Overall, this whole thing is more or less done.

**Comment by taw** [comment]
I finally fixed basics on common sheet issue.

**Comment by taw** [comment]
Closing this. All old packs work as expected, but calculations are not in indexer.

Newest few sets still lack showcase logic, but if anyone minds, they can fill a ticket with links to how it's supposed to work.
