### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#112]
One of the people on the Discord has requested a dark theme. I'm wondering how much work it would be to add one.

**Comment by taw** [comment]
In general it's a lot of hassle, but this site has really simple css, so I guess it would be doable?

I have vague plans to get rid of bootstrap and just use css grid directly at some point, I might add dark theme then.

**Comment by taw** [comment]
This might be a good idea. CSS isn't that long. Want to give it a try? If it looks decent, I'd totally implement dark theme switch.

**Comment by fenhl** [comment]
The dark theme should be enabled using [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme). I don't think a manual dark theme switch is necessary.

I'll see if I can write a quick dark theme. I would have expected this to already exist but I haven't been able to find anything so far.

**Comment by taw** [comment]
I think most users aren't aware of `prefers-color-scheme` switch existing, and most sites offer separate dark theme switches, so we'd probably need manual switch anyway.

Also it's experimental feature, with limited browser compatibility etc.

**Comment by fenhl** [comment]
The query will be in the next Edge, Chrome, and iOS Safari, which is [basically all major browsers](https://caniuse.com/#search=prefers-color-scheme) other than Android Chrome. The nice thing about it is that the user doesn't have to know about it, it will just automatically do the right thing based on the system theme. A manual toggle is only needed for people who want light system theme but dark websites or vice versa, or are on an incompatible browser. So even if we add a manual toggle, the default should still be to respect the media query, falling back to the light theme if the browser doesn't support it.

**Comment by taw** [comment]
Does Windows even have a dark theme switch?

**Comment by fenhl** [comment]
Yes. Settings → Personalization → Colors.

**Comment by taw** [comment]
I added dark mode support for select2 and decklist.

- [ ] I'm a bit unsure about contrast. I think think that blue on black might be a bit too dark. Once next Chrome comes out I'll use audit tools for it.
- [ ] It might be worth it adding manual dark mode selector anyway (saving it in a cookie or local storage) to the footer.

**Comment by taw** [comment]
I tried to see how difficult it would be to add a polyfill for systems/browsers which don't support `prefers-color-scheme`, and especially for users who don't know that such setting exists.

The idea is that JS would save that in `localStorage` etc.

[It's quite messy to mix JS and CSS like this](https://codepen.io/taw/pen/eYOBEOa).

Another alternative is to avoid mixing CSS and JS and just do this in header:

``` javascript
let colorScheme = localStorage.getItem("prefers-color-scheme") || (window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light")
$("body").addClass(colorScheme);
// or document.querySelector("body").classList.add(colorScheme)
```

This would lead to very simple CSS, since it would just use `body.dark` or `body.light`.

Of course there's still alternative of doing nothing, as users will eventually figure it out.

**Comment by taw** [comment]
Chrome accessibility audit thinks contrast is totally decent.

**Comment by taw** [comment]
It's been working for a while now so closing.
