### ISSUE TITLE
Search tokens

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#119]
It would be very useful to be able to search for what kinds of tokens a card can create. Perhaps a condition like `creates:` followed by a condition in a subset of the query syntax that makes sense for tokens. To do this, we will have to parse Oracle text, most likely in the indexer. An open question would be how to handle copy tokens.

# Examples

* `creates:*` for cards that can create tokens of any kind
* `creates:c=RG` for cards that can create red/green tokens
* `creates:t:artifact` for cards that can create artifact tokens, including cards with investigate or fabricate
* `creates:"Kobolds of Kher Keep"` for cards that can create tokens named Kobolds of Kher Keep
* `creates:(pow>4 or tou>4)` for cards that can create tokens with high power and/or toughness

**Comment by taw** [comment]
I thought about some fancy parser which would understand card syntax, even just for simplest queries like has:flying, this might be a bit difficult.

**Comment by fenhl** [comment]
Scryfall has data about related tokens: [example](https://api.scryfall.com/cards/f7f99431-ae43-4b68-82f0-faf940216c91?format=json&pretty=true) (in the `all_parts` field). It would also be awesome if tokens had their own pages like cards, though they probably shouldn't appear in search results by default.

**Comment by taw** [comment]
We have some data on tokens in mtgjson, but we don't really have any good way to get all the pics.

I might revisit this once I finish migrating to mtgjson v4.

**Comment by taw** [comment]
@fenhl Do you have any regexp or other solution that can figure this out? I'm not sure this is regular enough to be doable.

**Comment by fenhl** [comment]
Each MTG JSON set file has a `"tokens"` field, which contains data that's mostly structured like `"cards"`, with the notable addition of the `"reverseRelated"` field which lists the names of the cards that generate the token.

**Comment by taw** [comment]
If mtgjson does most of the work for us, I'm not opposed to it.

There's probably quite a few things in mtgjson that we don't index, search, or display. As a general rule, we should show all of that.

**Comment by taw** [comment]
Closing long inactive feature requests. Feel free to reopen if still interested.
