### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#12]
I would like to create a fork of this for the Custom Magic community, since we now have the Custom Standard and Custom Eternal formats. Could you please add a licence that would allow me to do this?

**Comment by taw** [comment]
Sure, I'll add some licence file. Forking is totally fine.

By Custom Magic you mean /r/custommagic on reddit or some other place?

Right now indexer is not terribly friendly towards adding custom magic sets, as it's pile of hack to make mtgjson work reasonably.

The rest of the engine shouldn't cause any issues, adding formats etc. is pretty straightforward. Hosting is also rather simple.

**Comment by fenhl** [comment]
I am talking about the [Custom Magic Discord](https://discordapp.com/invite/Twc6FX2), which is part of the [/r/custommagic](https://www.reddit.com/r/custommagic/) community. We are discussing the formats in [#custom-constructed](https://discord.gg/wfYh36s).

I'll see what I can do with it. Maybe these efforts will even result in contributions to this repo. I'll have to learn Ruby first though 😛

**Comment by taw** [comment]
[I added license file](https://github.com/taw/magic-search-engine/blob/master/LICENSE.md)
