### ISSUE TITLE
Convenient syntax for "castable using only mana of given colors"

### ISSUE THREAD

**Issue by glaebhoerl** [taw/magic-search-engine#121]
Most of the time when I'm building a deck, the single most relevant criterion for a card is "can I cast it using the colors of mana available in this deck". It's possible that this is already straightforwardly expressible with the existing syntax, and that I'm just missing something. Most of the time I overapproximate it by writing, say, `-m>=r -m>=b -m>=g` for a U/W deck, which basically works apart from a smattering of hybrid cards in two of the other colors (but false positives are less bad than false negatives). Searching for colors/mana a card, resp. its cost, does include, doesn't work very well, because it excludes colorless cards. Excluding other colors (e.g. `c!uw`) doesn't work very well, because it excludes cards I could be casting using hybrid mana. It would be much nicer to be able to just write `cast:uw` or whatever.

I *think* `cast:uw` would be exactly equivalent to `-m>=r -m>=b -m>=g -m>={r/b} -m>={b/g} -m>={r/g}` (which of course is too long to always be writing out directly), and analogously for other color combinations -- that is, any card whose cost doesn't include any mana symbol which I definitely couldn't produce. This handles Phyrexian and Shadowmoor hybrid mana correctly (any color can pay them). I'm not sure what the best way to handle *colorless* mana (that is, `{c}`) would be. Cards with *no* mana cost, or alternative costs, and so on, would also be interesting for completeness's sake, but can probably be considered out of scope.

I'm happy to try to implement this myself if you could kindly point me to where in the code it would make the most sense to do so (and any other helpful advice you may have:).

**Comment by taw** [comment]
Funny that you mention it, [as I wrote this before I even started mtg.wtf](http://t-a-w.blogspot.com/2013/03/simple-and-correct-algorithm-for.html).

Most people want to do `ci<=uw`, because this is typically a Commander question, and that's like 99% there. It's not quite what you want due to hybrid, mana costs in abilities, etc.

I guess we could add `cast:uw` which would deal with hybrid etc., so you always get [[Dismember]], [[Reaper King]] etc. for every cast query.

**Comment by glaebhoerl** [comment]
Yes, that's essentially what I'd want :) (excluding based on ability costs would in fact be undesirable, as there are plenty of cards which are useful even if an off-color ability can't be activated, the Mirage guildmages being a classic example)

Let me know if you'd prefer if I would take a shot at implementing this myself.

**Comment by taw** [comment]
Oh right, I kinda forgot about this. This really shouldn't be too hard, if you're interested.

**Comment by glaebhoerl** [comment]
No worries :) I'm not doing much deckbuilding these days so it's not too relevant to my interests at the moment.

**Comment by taw** [comment]
[`cast:` queries are now working.](https://mtg.wtf/card?q=cast%3Awrs)
