### ISSUE TITLE
Deck Visualizer issues

### ISSUE THREAD

**Issue by taw** [taw/magic-search-engine#124]
[The new feature is deck visualizer](http://mtg.wtf/deck/visualize). It needs some minor tweaks:

- [x] support for `SB:` (xmage)
- [x] support choosing specific printing (fallback to same set, then to most recent) - xmage uses syntax like `1 [EXP:9] Stomping Ground` or `SB: 1 [M12:145] Grim Lavamancer`
- [x] deal with non-UTF8 file uploads (textarea should already force UTF8)
- [x] file input to give feedback something was selected (needs bootstrap js which is not included because it wasn't needed until now)
- [x] link from footer
- [x] if uploaded file is binary or otherwise totally unrecognized, give error message
- [x] is "Deck Visualizer" actually the best name? should it be called Editor or Viewer or something?
- [x] if file is XML, [just use Cockatrice decklist parser I already wrote](https://github.com/taw/mtg/blob/master/lib/cockatrice.rb), or at least give better feedback

**Comment by fenhl** [comment]
Here's a real-world example of how people share Custom Standard decklists: <https://pastebin.com/ZBCaZfih>

**Comment by fenhl** [comment]
You can ignore the set codes on the basic lands, those are actually part of the card name.

**Comment by taw** [comment]
The problems I can see are `SB:` and `EAU`.

**Comment by fenhl** [comment]
EAU is the set code.

**Comment by taw** [comment]
Added support for that `SB:` tag, so everything except `EAU` should work now.

**Comment by taw** [comment]
So other than needing XMage style syntax `[EAU] Forest`, everything else about it works already.

I added error message when it gets binary data, and put it in the footer.

I'll add Cockatrice support at some point. It should works with XMage and MTGO decklists just fine.

**Comment by fenhl** [comment]
I should probably clarify that “EAU Forest” is a card name used to specify a certain printing of a basic land which people use to pick a specific artwork. Other examples of this include “ZebraPlains”, “RAK Mountain Fullart”, “Island of Esper”, etc. Support for these is probably out of scope for you, it's specific to custom Magic (and I have access to the data that creates these mappings but don't currently do anything with it).

**Comment by taw** [comment]
Right. If you want to do this, you can use XMage-style syntax `[EAU] Forest` or `[EAU:254] Forest` (also supporting `[EAU/254]`, putting that `[]` before or after card name, and a few variants like that, just in case).

I could add a few more regexps to this list if that's useful to people.

Anyway, it seems natural followup is to somehow export Sealed simulator packs into deck builder. Does that sound useful? Also how exactly could that work? Is there any online or software deckbuilder that's particularly good? I probably won't touch this anytime soon, but might be cool to gather some ideas.

**Comment by fenhl** [comment]
Yes, that's one of the things on my todo list.

**Comment by taw** [comment]
Just a link from opened packs to deck visualizer for them all is basically trivial (when sending those cards also send basically `<form><input type=hidden value=decklist><button>View as Deck</button></form>`).

Editor would be more work.

**Comment by taw** [comment]
Added that button to go from Sealed to deck preview.

It's extremely literal so stuff like this is included too:

```
1 [AKH:254] Forest
1 [AKH:251] Island
1 [AKH:253] Mountain
1 [AKH:266] Mountain [foil]
1 [AKH:255] Plains
1 [AKH:256] Plains
1 [AKH:257] Plains
```

**Comment by silasary** [comment]
It doesn't handle MTGO decks well, in either format.

The [.txt output](https://github.com/taw/magic-search-engine/files/3168409/9.-.Return.of.the.Allies.txt) fails to recognise the differentiation between main deck and sideboard.

And the [.dek output](https://github.com/taw/magic-search-engine/files/3168410/9.-.Return.of.the.Allies.dek.txt) obviously doesn't work, as it's an XML format.

MTGO also supports exporting as CSV, but I'm gonna just ignore that, as nobody ever uses it.

**Comment by taw** [comment]
Oh right, that single empty line separator between mainboard and sideboard. Kinda forgot about that. So I guess the things to do are:

- [ ] If deck is text format, and has no sideboard markers (by some regexp), but has one empty line in the middle, treat it as sideboard marker
- [ ] Add Cockatrice XML deck parser
- [ ] Add MTGO XML deck parser

I've never heard of that CSV format.

**Comment by taw** [comment]
Both XML formats are now supported. I'll just add some logic to figure out "empty line as sideboard separator" thing.

**Comment by silasary** [comment]
Feel free to not support it, I doubt anyone uses it.  But here's a [CSV format](https://gist.githubusercontent.com/silasary/f0c534e97ddc0d5250014d7a1247774a/raw/2e708da4ed703688382881a8f6e0304e493af246/demonic%2520rising.csv) deck.

**Comment by taw** [comment]
I've never seen the CSV format in the wild, so I'll add it only if someone actually wants it.

**Comment by taw** [comment]
Closing this since everything works as far as I know.
Feel free to report any issues you run into.
