### ISSUE TITLE
Saves Gatherer images as .png

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#126]
The card image endpoints on Gatherer don't have a suffix but they're actually JPEG files.

**Comment by taw** [comment]
Yeah, it's all wrong 😄

**Comment by fenhl** [comment]
Update: apparently some newer sets do actually use PNG images.

**Comment by taw** [comment]
I have very weak recollections of that, but maybe it was mix of JPG and PNG and I just used `.png` for everything and let server figure it out.

Most web servers should send correct mime headers regardless I think.

It might still be worth cleaning up at some point.

**Comment by fenhl** [comment]
It makes checking which images are actually images and which are the HTML of Gatherer's error page a bit more difficult, though I suppose that deserves its own issue.

**Comment by taw** [comment]
Are you getting errors from gatherer? Which set is giving you errors?

**Comment by fenhl** [comment]
All of them. Images for cards in a certain alphabetical range were error pages so I guess Gatherer went down during the initial download.

**Comment by taw** [comment]
OK, Gatherer seems to be down right now.
When it's up, I think all images should download correctly.

It's probably worth adding some error handling to download script.

**Comment by taw** [comment]
Do you still want something to be done about this?

**Comment by fenhl** [comment]
Yes, it's not a high priority but it would still be nice to have.

**Comment by taw** [comment]
The fetch script will now not save images unless it gets `200` response with `image/*` content type. It will print error instead (and try again if you rerun).
