### ISSUE TITLE
Merging back from Lore Seeker

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#138]
As you suggested in #71, here's a quick summary of [the changes between master and lore-seeker](https://github.com/fenhl/lore-seeker/compare/master...lore-seeker):

# Mergeable into master

- [ ] Canadian Highlander (#71)
- [ ] Format checks in deck visualizer (requires addition of Freeform format) and improved issue rendering
- [ ] `is:errata` (#75 is a bit outdated)
- [ ] New error pages (styled to look more like the website itself)
- [ ] `rulings` condition (checks number of rulings, conflicts with your new `rulings` condition, would be nice to have both)
- [x] `search-engine/lib/color_balanced_card_sheet.rb` makes `weights.nil?` a hard error since this indicates a set not generating boosters as specified
- [x] `is:mainfront`
- [x] Fixed color sort order in `search-engine/lib/sorter.rb` (fewer colors first, shards and wedges in the order WotC lists them)
- [ ] `CardController#list` (bot-friendly search API)
- [x] `is:custom` and `st:custom` conditions

# Requires Discord integration

* Discord login
* Default sort/view preferences (requires `sort:default`)

# Custom cards and other Lore Seeker-specific things

* Custom sets, including booster generators and CSS for new symbols
* Custom formats, including all the EXH infrastructure
* Preconstructed decks
* lsutil (tool for importing sets from MSE)
* Rules patch
* Cockatrice downloads
* Art crops for XMage
* Events (originally added for the now defunct Custom Standard Sealed League)
* Removed card name from card URLs, to be replaced with set versioning
* Using the current time instead of no time unless `dev?` (`true` on [dev.lore-seeker.cards](https://dev.lore-seeker.cards/) which is both new feature testing ground and next rotation spoilers page)
* Branding and contact page changes
* nginx and systemd integration (whether this is helpful depends on your setup)

**Comment by taw** [comment]
Do you want to make this a checklist, so we can check things off as we merge things or decide that we don't want to merge them?

Some quick notes:
* What's `is:mainfront` for? I thought it's a shortcut for `is:front is:primary`, but only first part of split card counts for `is:mainfront`.
* My color order was my best effort to match WotC color order in set numbering, but even WotC is not consistent, so I'm not terribly attached to any specific order.
* I can do `is:custom` / `st:custom` code, they'll just return no cards for me.
* `CardController#list` sounds good (then again, I had some Russian bot problems before 😅)
* Styled error pages sound good
* I use nginx, but our nginx setup will probably be different.

**Comment by fenhl** [comment]
Checklist added.

* The purpose of `is:mainfront` is to have an easy way of filtering down to one result per physical card, which `is:primary` doesn't accomplish due to its handling of split cards. For example, it's used in the Discord bot commands [`%mjt`](https://github.com/fenhl/lore-seeker-discord/wiki/%25mjt) and [`%momir`](https://github.com/fenhl/lore-seeker-discord/wiki/%25momir).
* I don't think modelling color order after set numbering is very useful given that `sort:number` exists as well. Starting with colorless is more intuitive for the Commander players I've asked (and searching for deck commanders is probably the most common use-case for `sort:color`).
* I guess adding `is:custom`/`st:custom` makes sense, especially since I'm not the only one in the custom Magic community maintaining a fork of this. Moved up into mergeable.
* For `CardController#list` I'd ideally like to return JSON so that the bot doesn't have to parse HTML. Haven't figured out how to get rid of the `application.html.haml` wrapper yet.
* Error pages probably need to be reworded since a few of them ask the user to contact me on Discord. Still worth upstreaming though.
* Moved nginx down to Lore Seeker-specific things.

**Comment by taw** [comment]
I merged a few minor things. Still a lot to go.

**Comment by fenhl** [comment]
I plan to open PRs for format checks and Canlander tomorrow. Maybe others too depending on how long that takes.

**Comment by taw** [comment]
I merged in a few other things, but they're related to custom/errata stuff, so can't even verify that I did it right.

**Comment by fenhl** [comment]
`is:front is:primary` is redundant, right? Since `is:primary` implies `is:front`

**Comment by taw** [comment]
Yes it is redundant.

**Comment by fenhl** [comment]
Didn't get around to working on this after all but I should have time next week.

**Comment by taw** [comment]
Oh right. Do you want to continue with it?

**Comment by fenhl** [comment]
Apologies, I've been busy with other things lately, but this is definitely still on my radar.

**Comment by taw** [comment]
@fenhl Are you still interested in this, or did you move on to other things? It looks like https://lore-seeker.cards/ is no longer up.

**Comment by fenhl** [comment]
I'm taking a break from Magic (not sure if and when I'll play again) and handed Lore Seeker over to @EikePeace, who has been having trouble setting everything up afaik.

**Comment by taw** [comment]
Closing long inactive feature requests. Feel free to reopen if still interested.
