### ISSUE TITLE
lore condition

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#139]
I just received a request to implement Scryfall's undocumented `lore:` condition, which searches card name, type line and flavor text. Since this isn't custom-specific, I'm putting it here.

**Comment by taw** [comment]
What are use cases for that?

We have undocumented `any:`, which is [very powerful](https://mtg.wtf/card?q=any%3Aizzet). Would that work well enough?

**Comment by taw** [comment]
By the way I'm totally fine with adding redundant feature for compatibility with scryfall and other such search engines. It's going to ease transition both ways, and costs very little.

**Comment by taw** [comment]
Done
