### ISSUE TITLE
Oversized Plane and Scheme cards returned when query string contains game:paper

### ISSUE THREAD

**Issue by pyyhttu** [taw/magic-search-engine#145]
By [syntax page's](https://mtg.wtf/help/syntax) definition, game:paper - says:

"card printings available as tournament-legal paper cards (**not oversized** or gold-bordered)"

I then search with: https://mtg.wtf/card?q=o%3Atarget+o%3Atwo+game%3Apaper+not+t%3Acreature+not%3Afunny+sort%3A-cmc

...but I still get oversized Planes and Schemes.

**Comment by taw** [comment]
Yeah, that looks like a bug, I'll look into fixing it.

**Comment by taw** [comment]
Should be fixed now.
