### ISSUE TITLE
Dungeon type

### ISSUE THREAD

**Issue by pyyhttu** [taw/magic-search-engine#146]
Forgotten Realms introduced a new card type, Dungeons: https://magic.wizards.com/en/articles/archive/feature/adventures-forgotten-realms-mechanics-2021-07-02

However, if I try to query them with t:dungeon, I only find "Dungeon Master": https://mtg.wtf/card?q=t%3Adungeon

In Scryfall t:dungeon returns the 3 dungeons, but interestingly, not the Dungeon Master: https://scryfall.com/search?q=t%3Adungeon

**Comment by taw** [comment]
It's a token, not a card, and we don't do tokens.

I guess these could be an exception.

**Comment by taw** [comment]
Dungeons added. I don't plan to add any other token types.
