### ISSUE TITLE
Website always returns 502 Bad Gateway

### ISSUE THREAD

**Issue by Wirox** [taw/magic-search-engine#149]
Currently the website doesn't seem to work at all.
Since a few hours ago I'm getting a 502 Bad Gateway response whenever I connect to https://mtg.wtf . It doesn't seem like it's a problem on my end – all websites like https://isitup.org/mtg.wtf say that mtg.wtf is down.

I believe everything worked correctly yesterday.

**Comment by taw** [comment]
Thanks for letting me know.

Looks like server process ran out of memory and crashed. Not sure why it happened. I just restarted it.
