### ISSUE TITLE
Scoped time travel

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#15]
It would be helpful if the `time:` syntax could be enclosed in parentheses to limit the time travel to the enclosed part of the query. Everything outside of the parentheses would be in relation to the current date as normal.

For example, to list all cards that rotated out of Standard with *Shadows over Innistrad*:

```
(time:OGW f:Standard) not (time:SOI f:Standard)
```

**Comment by taw** [comment]
The engine supports it (every time-aware operator has its own time), so it's just a matter of making query parser aware of it. `time:` on its own is already very advanced feature, so I didn't feel like it'd be worth the complexity.

Right now `sort:` `time:` and `++` are collected on query level. `sort:` and `++` would still need to be at that level.

So to make this work, it would need `ConditionTime`, not just doing it on top level, which is the easy part.

The only nontrivial part is that `time:` would also teed to propagate time up to `()` boundary but no further.

**Comment by taw** [comment]
I refactored parser/tokenizer/metadata code as it was messy, and as a result it was possible to add this functionality. [Enjoy](http://mtg.wtf/card?q=(time%3AOGW+f%3AStandard)+not+(time%3ASOI+f%3AStandard))
