### ISSUE TITLE
e:nec not returning Neon Dynasty Commander cards

### ISSUE THREAD

**Issue by pyyhttu** [taw/magic-search-engine#151]
To reproduce: https://mtg.wtf/card?q=e%3Anec returns 362 cards but no Neon Dynasty Commander cards, while https://scryfall.com/sets/nec?as=grid&order=set returns the set correctly with 179 cards.

Actually, mtg.wtf doesn't seem to contain any of the Neon Dynasty Commander cards, as https://mtg.wtf/card?q=chishiro returns nothing, but should return https://scryfall.com/card/nec/1/chishiro-the-shattered-blade

**Comment by taw** [comment]
There were some technical issues that delayed the update. NEC is now on mtg.wtf.
