### ISSUE TITLE
is:vanilla returns also lands

### ISSUE THREAD

**Issue by pyyhttu** [taw/magic-search-engine#153]
Heeding today's cardboard crack comic, decided to check what other recent vanilla creatures have been printed: https://mtg.wtf/card?q=is%3Avanilla+sort%3Areleased

Noticed that is:vanilla also returns lands, namely these: https://mtg.wtf/card?q=is%3Avanilla+t%3Aland

Expectation is that is:vanilla would only return vanilla creatures, at least that is what scryfall returns: https://scryfall.com/search?q=is%3Avanilla

**Comment by taw** [comment]
I use "vanilla" to mean "with nothing in text box". Not sure if including lands is the expectation or not.

The ruling on Muraganda Petroglyphs says:

> 2021-03-19 If a land with a basic land type becomes a creature, the intrinsic mana ability it has stops Muraganda Petroglyphs from applying to it.

So I guess by this logic basic lands don't count.

**Comment by taw** [comment]
As a followup question should Dryad Arbor be `is:vanilla`?

**Comment by pyyhttu** [comment]
I guess this comes down to what has become an acceptable definition of vanilla in the community. In my mind it referred originally only to creatures without card text. For the two special cases I turned to gatherer to check if they have Card Text paragraph mentioned on the page in its Oracle section (noticed that vanilla creatures do not):

[Dryad Arbor](https://gatherer.wizards.com/Pages/Card/Details.aspx?printed=false&multiverseid=509642) -> Card Text (in form of reminder) -> not vanilla.
[Embereth Shieldbreaker](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=473084) -> no Card Text ->  vanilla.
[Infinity Elemental](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=479445) -> Card Text (in form of reminder) -> not vanilla.

Also now noticed Scryfall [syntax page](https://scryfall.com/docs/syntax) refers with vanilla only to creatures, and they *do* return Infinity Elemental as vanilla, which per the gatherer method above, should not be vanilla.

**Comment by taw** [comment]
I don't think remainder text can matter, as different printings of same card will have or not have remainder text.

Anyway, made lands not match is:vanilla.
