### ISSUE TITLE
Underdark dungeon

### ISSUE THREAD

**Issue by pyyhttu** [taw/magic-search-engine#154]
Referring to #146: Requesting to add Undercity dungeon to query returned by https://mtg.wtf/card?q=t%3Adungeon

Undercity as fourth dungeon was introduced by Commander Legends: Battle for Baldur's Gate: https://magic.wizards.com/en/articles/archive/feature/commander-legends-battle-baldurs-gate-mechanics-2022-05-18

Edit: And it might make sense to add it as a double faced card, as it seems to have on the flip side the rather helpful and relevant  Initiative, as depicted also here: https://scryfall.com/search?q=t%3Adungeon

**Comment by taw** [comment]
[Added as a single faced token](https://mtg.wtf/card?q=t%3Adungeon).

Maybe we should have some indication which room connects where, as text doesn't show connections.

**Comment by pyyhttu** [comment]
Yes, well spotted, and would make sense, as the connections are now shown by Oracle too, e.g. https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=530447

**Comment by taw** [comment]
Remainder text kept on dungeons. That should be all.
