### ISSUE TITLE
Querying minsc &

### ISSUE THREAD

**Issue by pyyhttu** [taw/magic-search-engine#157]
Small thing, but noticed that querying with minsc & returns nothing: https://mtg.wtf/card?q=minsc+%26
While the same works at scryfall: https://scryfall.com/search?q=minsc+%26

Which raises the question if that '&' is not properly taken into account in search syntax.

**Comment by taw** [comment]
`&` is a synonym for `//`, and is used for DFC and other multipart searches like [`t:human // t:insect`](https://mtg.wtf/card?q=t%3Ahuman+%2F%2F+t%3Ainsect), [`ice & fire`](https://mtg.wtf/card?q=ice+%26+fire). Both `//` and `&` are often used on cardlists, so I support both, even though I only put `//` on syntax help page to avoid duplication.

The parser basically has a list of exceptions to this, like queries like [R&D](https://mtg.wtf/card?q=r%26d) work. I guess I'd need to add an exception for Minsc.

**Comment by pyyhttu** [comment]
> & is a synonym for //

Ah, wasn't aware of that, as indeed: didn't see it documented at https://mtg.wtf/help/syntax

**Comment by taw** [comment]
Fixed now by adding special case for it.
