### ISSUE TITLE
missing 2022 starter kit decks

### ISSUE THREAD

**Issue by drewmullen** [taw/magic-search-engine#161]
Magic: The Gathering 2022 Starter Kit: https://www.amazon.com/Magic-Gathering-Starter-Ready-Play/dp/B09XF8DTD7

not sure how you go about generating the json payloads in data/sets/ but i could provide the file if theres docs on that process

**Comment by taw** [comment]
[The process is here](https://github.com/taw/magic-preconstructed-decks).

If you point url2txt at the right url, it gets you the decklists, and you can drop the to the right folder and PR them. (just add release date if it's different than set's release date).

If that's too much work, just create github issue and post decklist urls, preferably official ones from wizards.com.
