### ISSUE TITLE
New Print Sheet System

### ISSUE THREAD

**Issue by taw** [taw/magic-search-engine#167]
Most sets don't need any print sheet information, and fairly simple queries can be done manually.

For sets that do need that, there are 4 different systems:

* LEA/LEB/2ED/3ED - lists like `2ed/19/disenchant`
* MB1 (also used by CMB1/CMB2) - lists with just card names 
* official Wizards lists - lists like `Balduvian Dead               Mike Kimble                    U2` (which are then patched as they contain a lot of mistakes)
* generated by code like for IKO

What needs to be done:

- [x] new format defined
- [x] add SIS print sheets
- [x] add PLIST print sheets
- [x] maybe change IKO to use queries like `has:showcase` instead of print sheets, I don't think there's that much value there
- [ ] migrate MB1
- [ ] migrate LEA/LEB/2ED/3ED
- [ ] maybe migrate Wizards official lists to new format, and leave the originals (plus explanation of patches) just for reference

Most obvious possible new formats:

* file like `data/print_sheets/<set>.txt` with lines like `Forest \t 300 \t L2`
* file like `data/print_sheets/<set>/<sheet>.txt` with lines like `Forest \t 300 \t 2` - last ones could be optional if unambiguous (in such case MB1 already uses this format except for file names)

Possible followup:

- [x] queries like `sheet:mb1/RA` etc.
- [ ] many sets have subsheets for commons like A, B, C etc. commons. This could be doable in this new system
- [ ] we actually have commons order information for many sets. I don't think we want to get into this.

**Comment by taw** [comment]
New format defined:

Files like `data/print_sheets_new/leg.txt` with contents like

```
```

**Comment by axxroytovu** [comment]
> * [ ]  maybe change IKO to use queries like `has:showcase` instead of print sheets, I don't think there's that much value there

What needs to be done here? Can I help build this at all? I was planning on deep diving on boosterfun in draft boosters work once you had finished cleaning up the code base.

**Comment by taw** [comment]
For IKO I wrote some code that basically marks every `is:showcase` as U1, `has:showcase -is:showcase` as U2, and `-has:showcase` as U3 (and so on for other rarities), so booster logic is trivial and just checks the print sheet information.

Except back then I didn't have `is:showcase`, and IIRC mtgjson didn't even mark showcase cards as such, so it was some card number range logic. [Here's the code](https://github.com/taw/magic-search-engine/blob/master/indexer/lib/patches/patch_showcase.rb).

If we find a really good way to do other boosterfun, maybe we can migrate IKO to that new system, but I'd recommend just giving other sets a try first to see if we can come up with something better.

**Comment by axxroytovu** [comment]
I updated the pull request https://github.com/taw/magic-search-engine/pull/163 using the fact that mtgjson does have `"promoType": ["boosterfun"]` for its printings. By adding a few extra logic checks (extended art is also classed as boosterfun, and lots of foil-only cards are classed as boosterfun) it should 100% track to what we need. That has been working nearly perfectly for all the simpler sets. Ikoria is weird with the godzilla cards, and ONE has the prototype praetors, but those were going to be headaches no matter what system we use.

**Comment by taw** [comment]
After yaml code rewrite, IKO sheet codes aren't really used anymore, so they can be dropped.

**Comment by axxroytovu** [comment]
```
  def explicit_sheet(set_code, print_sheet_code, foil: false, count: nil)
    cards = @db.sets[set_code].printings.select{|c|
 >>>  c.in_boosters? and c.print_sheet and c.print_sheet.scan(/[A-Z]+/).include?(print_sheet_code)
    }
```

Is this `c.in_boosters?` required? It would be useful to have this be optional for cases where we need a sheet to include boosterfun cards. Example with non-functional code: https://github.com/taw/magic-search-engine/pull/196

**Comment by taw** [comment]
Nope, it shouldn't be there anymore. I just need to verify that it doesn't change any existing code.

**Comment by taw** [comment]
I removed that check, it doesn't do anything anymore.

**Comment by taw** [comment]
I think it's good enough. I'll just leave old sheets where they are, there's not much value in rewriting them. Maybe I'll clean it all up in some future refactoring.
