### ISSUE TITLE
One with Nothing returns One with Nature

### ISSUE THREAD

**Issue by pyyhttu** [taw/magic-search-engine#17]
To reproduce: 
1. Query One with Nothing
2. Card "One with Nature" is returned.

Noticed that if I query "One with Nothing" (with quotes), the correct card is returned.

**Comment by taw** [comment]
That was a bug where "not" starting a word was treated as "not" operator, so it parsed that as "one with not hing". As the only "one with" card without "hing" in name is "One with Nature", that's how it got there.

[It's fixed now](http://mtg.wtf/card?q=one+with+nothing).
