### ISSUE TITLE
`promotype:` query support

### ISSUE THREAD

**Issue by taw** [taw/magic-search-engine#171]
Since mtgjson has this data, we might just as well expose it.

It also covers `is:boosterfun` as it's basically `promotype:boosterfun`.

(index should have `promo_type` or `promotype`, there's no camelcase there)

**Comment by axxroytovu** [comment]
Do you want the boosterfun pack logic to exist in the pack YAML queries, or in the search?

As an example for ONE:

- Archfiend of the Dross - printings 304 and 434 are tagged as promo_type: boosterfun, but only 304 can appear in draft boosters. 434 appears in the oil slick collector booster slot
- Argentum Masticore - printing 393 is tagged as promo_type: boosterfun, but only appears in the extended art collector booster slot.

These could be resolved by making the YAML search more comprehensive, but then has:boosterfun would flag Argentum Masticore as having a boosterfun printing. Or we can implement more logic to is:boosterfun, but then it no longer tracks 1-1 with promo_types:boosterfun.

**Comment by taw** [comment]
I think `is:boosterfun` should be just `promotype:boosterfun` and that should just be whatever mtgjson says.

If we need additional query types, we should come up with them, with some good definitions.

**Comment by taw** [comment]
`promo:` queries added, very similar to how `frame:` query works. There's a lot of them.

[promo:buyabox](https://mtg.wtf/card?q=promo%3Abuyabox), [promo:boosterfun](https://mtg.wtf/card?q=promo%3Aboosterfun) etc.

All of them are also aliased to `is:` and `not:`, as there are no conflicts. (`frame:` has a few conflicts, where `is:X` already means something else).
