### ISSUE TITLE
Autofocus search field

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#18]
It would be helpful if the search field could automatically take keyboard focus when you start typing on the page. Something like [this](http://stackoverflow.com/a/21825545/667338) maybe.

**Comment by taw** [comment]
mtg.wtf used to have autofocus feature (via `autofocus` attribute, no javascript needed).

The problem was that on some android browsers autofocusing a field makes it spawn virtual keyboard covering half the screen, which completely wrecks usability.

So I disabled it on everything except main page (where that virtual keyboard is not a big deal).

I guess this javascript workaround of focusing on typing might just work.

**Comment by taw** [comment]
Well, I've taken a look at that stackoverflow thread, and it would be bad if we hijacked stuff like alt-tab, cmd-1 etc.

**Comment by fenhl** [comment]
I didn't realize you could do that with JavaScript. If that's the case, maybe we can use the other answer where only `s` focuses the search field, and expand it to react to `!` as well and add the `!` to the search field in that case, for looking up cards by name more efficiently.

**Comment by taw** [comment]
Well, if you press tab, it should focus you on search field on every page of mtg.wtf, so the whole thing would only save one keystroke.

**Comment by fenhl** [comment]
Ah, I wasn't aware of that. I did try pressing `s` though, since I know that works on some other websites, so that would have been more discoverable, at least for me.

While we're at it, having left/right arrow keys navigate between pages would also be useful.

**Comment by taw** [comment]
For pagination? I guess I could add some shortcuts. Or we could just autoload more results like facebook.

The problem is that you never know if they'll interfere with some browser shortcuts. For example some video sites have ctr+number move video position, and that interferes with browser tabs.

**Comment by fenhl** [comment]
Shortcuts that don't use ctrl/alt/cmd should be fine though, no?

**Comment by taw** [comment]
_Probably_.

One obvious counterexample is that space is basically a page down key, and most laptops don't have separate page down - but I've seen a lot of websites that screw that one up.

**Comment by taw** [comment]
OK, now it autofocuses on all non-touchscreen devices. It might very well act funny on Surface and laptops with touchscreens, but I'll revisit the problem if they ever get popular.
