### ISSUE TITLE
Color indicator search

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#19]
One of the few features magiccards.info has that's missing here is searching by color indicator, e.g. `in:WU` for any card that has a white and/or blue color indicator, e.g. [Ancestral Vision](https://mtg.wtf/card/ddajvc/21) or [Transguild Courier](https://mtg.wtf/card/di/168).

**Comment by taw** [comment]
I guess I could add that. The one on magiccards.info is sort of broken, like `in:rg` returns [[Garruk, the Veil-Cursed]] who's G/B.

For now you can get most of that functionality with queries like [`c!g -mana>=0`](http://mtg.wtf/card?q=c%21g+-mana%3E%3D0). (color exactly green, doesn't have mana cost). That works for DFCs, suspend cards, and Dryad Ambor (but not for [[Tranguild Courier]], pacts, or Kobolds).

And I guess it would be nice to have some kind of "has no mana cost" query.

**Comment by fenhl** [comment]
I think getting exactly RG color indicators should be `ci!RG` for consistency with the other operators.

As for no mana cost, how about `mana=` with a blank right side, or maybe `mana={}`?

**Comment by taw** [comment]
[`mana=` and `mana={}`](http://mtg.wtf/card?q=mana%3D%7B%7D+c%3Ar) now work.

**Comment by taw** [comment]
It's done. I made it match exactly, as it seems to makes more sense this way (and `c:` is a bit of a mess, which would be done differently if it wasn't for trying to get some level of MCI compatibility).
