### ISSUE TITLE
is:reprint doesn't match mtgjson for MH2

### ISSUE THREAD

**Issue by axxroytovu** [taw/magic-search-engine#194]
MTGJson includes an isReprint field in their files. Can this replace `condition_is_reprint.rb`?

MH2 rare cards are flagged as reprints even when they are not, because PMH2 was "released" earlier and the promo cards are being flagged as the original printing.

**Comment by taw** [comment]
What do they define as a "reprint" vs "not reprint"?

I don't recommend relying on `is:reprint` for anything, mtgjson data on release dates has been unreliable.

**Comment by taw** [comment]
By the way card age is currently defined in code as counting "first printing except PPRE set", due to past mtgjson issues (it used to be a mtgjson set with Prerelease promos, now it's split per-set). So I did a similar workaround before, the code just rot and no longer works.

**Comment by taw** [comment]
I also opened https://github.com/taw/magic-search-engine/issues/195 for related issues. There are probably a few more fields we might want to index.

**Comment by axxroytovu** [comment]
> What do they define as a "reprint" vs "not reprint"?
> 
> I don't recommend relying on `is:reprint` for anything, mtgjson data on release dates has been unreliable.

It looks like they're pulling the reprint flag from Scryfall.

The reason I wanted to use the `is:reprint` tag is because the reprint/new boosterfun cards are mixed together for MH2 but appear in different slots. Soul Snare is conveniently placed at the end of the normal frame cards, but is nestled between Sanctifier en-Vec and Timeless Dragon for the old border cards. Manually pulling out each of the reprint boosterfun cards would be an absolute nightmare.

**Comment by taw** [comment]
There's pretty big difference between these two conditions (age>0, isReprint flag):

* [false, false]=>30506
* [true, true]=>42067
* [false, true]=>4533
* [true, false]=>659

Sets affected by changes, losing flag:

* 5dn=2, aer=5, afr=2, ala=1, anb=4, apc=2, arb=1, avr=11, bfz=6, bng=11, bok=2, bro=5, c18=4, chk=2, con=1, csp=2, dgm=7, dis=2, dka=11, dmu=2, dst=2, dtk=3, eve=1, exo=1, frf=15, fut=1, gpt=3, grn=2, gtc=12, hou=3, inv=1, isd=8, jou=12, jud=1, ktk=6, lgn=3, lrw=1, m10=3, m11=2, m12=4, m13=5, m14=8, m15=18, m19=1, mbs=5, mh2=186, mmq=2, mor=1, mrd=2, ncc=150, nem=1, nph=4, ody=1, ogw=3, ons=1, opca=6, ori=10, pbfz=2, pcy=1, plc=1, pls=2, ptk=1, rav=2, rtr=6, scg=2, shm=1, snc=4, soi=7, sok=2, som=6, sth=1, ths=16, tmp=1, tor=1, tsp=1, uds=1, ugl=5, ulg=1, unh=6, usg=3, ust=1, vis=12, war=2

Gaining flag:

* cp3=1, ddf=2, ddj=6, ddl=6, ddn=6, ddp=6, ddq=6, drb=1, exp=5, f03=1, f11=1, f12=2, f13=4, f14=5, f15=5, f16=4, f17=3, gdy=5, j17=1, jgp=2, med=4, mgb=10, mp2=8, mps=7, o90p=1, oafc=4, oc13=10, oc14=5, oc16=5, oc17=4, oc18=4, oc20=5, ocmd=10, olep=5, ovoc=2, p30a=1, p5dn=1, paer=59, pafr=237, pakh=84, pal03=3, pal04=8, pal05=3, pal06=4, pala=1, pana=2, papc=1, parb=2, past=1, pavr=5, pbbd=22, pbng=9, pbok=3, pbro=149, pchk=1, pclb=92, pcns=1, pcon=2, pcsp=1, pdci=4, pdgm=6, pdis=2, pdka=7, pdmu=144, pdom=100, pdp14=2, pdp15=2, pdst=1, pdtk=50, peld=148, pemn=77, peve=2, pexo=1, pfrf=37, pfut=2, pgpt=2, pgrn=78, pgtc=9, phel=5, phop=2, phou=61, piko=136, pinv=1, pisd=7, pjou=10, pjud=1, pkhm=168, pkld=75, pktk=52, plg21=3, plgn=1, plrw=2, pm10=3, pm11=2, pm12=3, pm13=5, pm14=4, pm15=12, pm19=76, pm20=116, pm21=102, pmbs=4, pmei=6, pmh1=1, pmh2=75, pmid=166, pmmq=1, pmor=2, pmrd=1, pncc=76, pnem=1, pneo=155, pnph=4, pody=1, pogw=65, pone=146, pons=1, pori=43, ppcy=1, pplc=2, ppls=1, pptk=1, prav=2, pres=1, prix=102, prm=12, prna=72, proe=3, prtr=9, ps14=4, ps15=10, pscg=1, psdc=2, pshm=2, psnc=156, psoi=97, psok=2, psom=3, pss1=5, psth=1, pstx=180, pthb=124, pths=10, ptmp=1, ptor=3, ptsp=2, puds=1, pulg=2, pusg=1, pust=1, pvow=118, pw12=3, pwar=168, pwwk=3, pxln=120, pzen=3, pznr=166, sta=2, ugin=13, v10=1, v11=1, xana=4

**Comment by taw** [comment]
By the way are these the queries you're looking for?

* e:mh2 frame:old alt:(e:mh2 number=262-303)
* e:mh2 frame:old -alt:(e:mh2 number=262-303)

**Comment by axxroytovu** [comment]
That would work, I didn't think of using `Alt`.

**Comment by axxroytovu** [comment]
After a spot check of your lists of gained/lost reprint flag, it looks like the scryfall version is the more accurate one. I haven't done an exhaustive check, but the flag does appear to be correct for all the ones I looked at.

**Comment by taw** [comment]
Well, their concept of a "reprint" is definitely not the obvious one. Like oc16 cards came literally in the same box as c16 cards, and somehow they're a "reprint" etc.

It looks like they just select something as first printing (earliest non-promo printing?), and mark every other printing as a reprint regardless of relative date.

Maybe that's more useful than literal "earliest printing by date".

**Comment by taw** [comment]
I restored `is:reprint` to its intended functionality it used to have:

* "promo" flag is per set (so showcases etc. are not promos for this; not like it would matter)
* if card has any printing in non-promo set, pick oldest
* otherwise, if card only has printings in promo sets, pick oldest
* any printing same age or older than that is not a reprint; any printing newer than that is a reprint

This doesn't match mtgjson/scryfall, but I think this should match what I'd describe as a reprint.

It should deal with cases like prerelease promos, OCxx cards etc. correctly.

Are there any problems with this system? We have an option to switch to using mtgjson flag if this doesn't work.

**Comment by taw** [comment]
I guess it would make sense to treat STA like other promo sets for this, but there's no flag for that like `st:reprint` yet.

What else would qualify for `st:reprint`? [It's basically all done here](https://github.com/taw/magic-search-engine/blob/master/indexer/lib/patches/patch_set_types.rb), and that's really messy. It would be nice to clean it up at some point.

**Comment by axxroytovu** [comment]
I think the general consensus for the naming of the bonus sheet sets has been "masterpiece", so that might be a good thing to add. That would be STA, BRR, MUL, EXP, MPS, and ZNE

The other easy flag is "masters", which apart from Cryptic Spires has entirely been reprints.

**Comment by taw** [comment]
I might clean it up at some point. A few of them are used in the code (like standard, modern, promo, funny, custom), a lot of them drive integration test logic (like booster, deck), some might be useful for people searching (like `st:commander`), and a lot more are basically pointless (I doubt anyone used `st:"premiere shop"` even once).

Like many things in the indexer, it's another leftover from mtgjson changing its mind multiple times.

If you need any specific addition to the list, feel free to PR it. Otherwise it's low priority cleanup task.

**Comment by axxroytovu** [comment]
Yeah it's low priority now that you've updated the logic above. MH2 seems to be working minus some bugs that I'm struggling with. Wizards why do you need to have rarity shifted borderless cards they're such a pain.

**Comment by taw** [comment]
I'll close it as good enough for now.
