### ISSUE TITLE
Mana costs in rulings are not displayed correctly

### ISSUE THREAD

**Issue by FM-96** [taw/magic-search-engine#20]
For an example see the card [Grand Arbiter Augustin IV](http://mtg.wtf/card/di/112/Grand-Arbiter-Augustin-IV):

The rulings *should* read

- 2006-05-01 Spells you cast that are both blue and white cost {2} less to cast.
- 2006-05-01 This reduces only generic mana portion of mana costs. A spell you cast with mana cost {1}{W}{U} will cost {W}{U} to cast.

But instead they actually read

- 2006-05-01 Spells you cast that are both blue and white cost less to cast.
- 2006-05-01 This reduces only generic mana portion of mana costs. A spell you cast with mana cost will cost to cast.

**Comment by fenhl** [comment]
Caused by upstream issue mtgjson/mtgjson#279.

**Comment by taw** [comment]
Yeah, I just checked, it's mtgjson problem again, hopefully they fix it.

**Comment by taw** [comment]
Problem got fixed upstream, and it works here too.
