### ISSUE TITLE
Link to other meld half

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#21]
[Graf Rats](https://mtg.wtf/card/emn/91a) says “Card has other part: [Chittering Host](https://mtg.wtf/card/emn/96b)” but it should also mention [Midnight Scavengers](https://mtg.wtf/card/emn/96a).

**Comment by taw** [comment]
The "Card has other part:" feature is meant to link to what's on the other side of the card (flip, split, or DFC).

It's sort of unclear what's the right way to display meld cards. By current logic Midnight Scavengers is not on the other side of Graf Rats, it just combos with it (more like Tron lands or Bogbrew Witch stuff than split cards), but it could be change if treating them as multipart cards makes sense.

**Comment by taw** [comment]
So I finally introduced the feature I wanted ages ago - related cards. This covers this case and also a lot others like:

* [Throne of Empires](https://mtg.wtf/card/m12/221/Throne-of-Empires)
* [Nissa's Chosen](https://mtg.wtf/card/zen/171/Nissas-Chosen)
* [Bogbrew Witch](https://mtg.wtf/card/m14/88/Bogbrew-Witch)
* [Renowned Weaponsmith](https://mtg.wtf/card/frf/48/Renowned-Weaponsmith)
* [Godsire](https://mtg.wtf/card/ala/170/Godsire)
* [Wastes](https://mtg.wtf/card/ogw/183/Wastes)

any many others.

There are some weird cases too like [Kobolds of Kher Keep](http://mtg.wtf/card/lg/226/Kobolds-of-Kher-Keep), [Arrest](http://mtg.wtf/card/rtr/3/Arrest), but I feel they're worth keeping too.
