### ISSUE TITLE
Missing set jumpstart packs for ONE and MOM

### ISSUE THREAD

**Issue by axxroytovu** [taw/magic-search-engine#216]
- https://magic.wizards.com/en/news/announcements/phyrexia-all-will-be-one-jumpstart-booster-themes-and-card-lists
- https://magic.wizards.com/en/news/announcements/march-of-the-machine-jumpstart-booster-themes-and-card-lists

I can add these, but I don't know what your sorting methodology is for the decks.json file is.

**Comment by taw** [comment]
Fo precons:

* all data is here - https://github.com/taw/magic-preconstructed-decks
* decks are basially text files in the standard deck text format everyone uses, except for some optional metadata support like `[foil]` `[set:number]` `COMMANDER:` etc.
* https://github.com/taw/mtg has url2txt tool that can turn url of any popular MTG site into a bunch of compatible text files, with most of the right annotations
* for the almost-jumpstart decks, you'll need to manually correct the "Random rare or mythic rare" lines to proper annotation as this is not a real card. Also if they work like BRO Jumpstart, then it's actually "random <color> rare or mythic rare"

Example of correct file: https://github.com/taw/magic-preconstructed-decks/blob/master/data/jumpstart-19/bro/Infantry%201.txt

**Comment by axxroytovu** [comment]
Should be complete with https://github.com/taw/magic-preconstructed-decks/pull/32
