### ISSUE TITLE
Search breaks with non-ascii quotation marks

### ISSUE THREAD

**Issue by axxroytovu** [taw/magic-search-engine#224]
This is mostly an issue with searching on mobile, which automatically uses U+201C, and U+201D quotes instead of the standard ascii U+0022.

https://mtg.wtf/card?q=subset%3A%22monster+movie+marathon%22 - works
https://mtg.wtf/card?q=subset%3A%E2%80%9Cmonster+movie+marathon%E2%80%9D - broken

**Comment by taw** [comment]
Fixed now. Are there any other weird characters which we should un-substitute?

**Comment by axxroytovu** [comment]
I don't know how single quotes/apostraphes/graves are treated but that might be cleaned up. Maybe em-dash/en-dash/hyphen? I can't think of any situation where those would cause the system to actually crash but they are commonly confused for each other.

**Comment by taw** [comment]
I'll close this issue. If you find another character causing troubles, just let me know.

**Comment by axxroytovu** [comment]
Will do, glad it was an easy fix.
