### ISSUE TITLE
Missing related cards

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#23]
The related cards feature introduced to fix #21 is great, but incomplete: [Helm of Kaldra](https://mtg.wtf/card/5dn/131) fails to link to [Shield of Kaldra](https://mtg.wtf/card/ds/139) and [Sword of Kaldra](https://mtg.wtf/card/mi/251).

**Comment by taw** [comment]
Yeah, my regexp missed this one.

**Comment by taw** [comment]
Fixed.
