### ISSUE TITLE
Search by name, advanced

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#24]
It would be helpful to be able to search by exact name in addition to other queries, e.g. to link to a combo:

```
name="Painter's Servant" or name=Grindstone
```

And this feature would be helpful for the [MM3 number crunch](https://docs.google.com/spreadsheets/d/1XFq8oiGSxdwFzbEtkVJA8uWKQ7aknrAHdfOilKTDtDo/edit#gid=0) currently going on: lexical name comparison. For example, to find the possible cards in slot 247:

```
f:Modern print<=M14 t:land name>"Selesnya Guildgate" name<"Simic Guildgate"
```

**Comment by taw** [comment]
If it's for number crunch, we should probably match whichever naming system they use (with AE, spaces, diacritics etc.), which might be different than `String` sort order. Anybody bothered documenting that?

**Comment by taw** [comment]
I tried to use this code to evaluate print order, and it's not very reliable.

A lot of these are issues like DFCs, split cards, planeswalker decks, special sets like FTV etc., so inherently unpredictable.

Do you have any input on the order key?

```
#!/usr/bin/env ruby

require_relative "../lib/card_database"

class TestOrder
  def initialize
    json_path = Pathname(__dir__) + "../data/index.json"
    @db = CardDatabase.load(json_path)
  end

  def call
    @db.sets.each do |set_code, set|
      printings = set.printings.sort_by{|n| [n.number.to_i, n.number] }
      printings.each_cons(2) do |a, b|
        if (order_key(a) <=> order_key(b)) == 1
          puts "#{set_code} #{a.name} #{b.name}"
        end
      end
    end
  end

  def order_key(card)
    # 1809 order violations
    [
      card.colors == "w" ? 0 : 1,
      card.colors == "u" ? 0 : 1,
      card.colors == "b" ? 0 : 1,
      card.colors == "r" ? 0 : 1,
      card.colors == "g" ? 0 : 1,
      card.colors == ""  ? 1 : 0,
      card.types.include?("land") ? 1 : 0,
      card.types.include?("basic") ? 1 : 0,
      card.name == "Plains" ? 0 : 1,
      card.name == "Island" ? 0 : 1,
      card.name == "Swamp" ? 0 : 1,
      card.name == "Mountain" ? 0 : 1,
      card.name == "Forest" ? 0 : 1,
      card.name.downcase.gsub(/[,' ]+/, " "),
    ]
  end
end

TestOrder.new.call
```

**Comment by fenhl** [comment]
Ordering cards by how they would be numbered in a new set is an interesting, though much harder feature. I'll have to look into it more closely.

**Comment by taw** [comment]
I got the order down to 1354 order violations - script is `bin/test_order` if you want to play with it.

I sort of don't think we can go all the way, like [7th edition mixed basics and nonbasics](http://mtg.wtf/set/7e?page=14), Commander decks reset order every deck, [planeswalker deck only cards go after regular cards](http://mtg.wtf/set/ori?page=12), early sets don't have collector's numbers so we just make them up etc.

**Comment by taw** [comment]
Rechecking old issues. I think naive `name>` (ignoring colors etc.) would probably be fine, and I got derailed into trying to come up with perfect system.

It just needs a quick check with regards to how WotC handles punctuation, capitalization etc.

**Comment by taw** [comment]
Both work now:
* [`name="Painter's Servant" or name=Grindstone`](http://mtg.wtf/card?q=name%3D%22Painter%27s+Servant%22+or+name%3DGrindstone)
* [`f:Modern print<=M14 t:land name>"Selesnya Guildgate" name<"Simic Guildgate"`](http://mtg.wtf/card?q=f%3AModern+print%3C%3DM14+t%3Aland+name%3E%22Selesnya+Guildgate%22+name%3C%22Simic+Guildgate%22)

It uses what's inferred to be WotC ordering scheme (case insensitive, `'` and `,` ignored, space treated as character) but there's probably some rare cases where that's not the full algorithm.

If you notice any ordering violation in modern set, please bug report.
(excluding obvious last minute stuff like [It That Betrays](http://mtg.wtf/card/roe/7/It-That-Betrays))

**Comment by silasary** [comment]
In the provided `f:Modern print<=M14 t:land name>"Selesnya Guildgate" name<"Simic Guildgate"`,  I assume that Selesnya Guildgate itself should not be visible?

**Comment by taw** [comment]
If you use `name>=` then yes. If you use `name>` then no.
