### ISSUE TITLE
Link MTGJSON SealedProduct UUIDs to Decks

### ISSUE THREAD

**Issue by ZeldaZach** [taw/magic-search-engine#247]
The current file structure of decks_v2 has 
```
    "name": "Bertrand Lestree, Finalist",
    "type": "Pro Tour Deck",
    "set_code": "ptc",
    "set_name": "Pro Tour Collector Set",
    "release_date": "1996-05-01",
```

I'd like to get a "sealedProductUuids" List[str] that contains the MTGJSON UUIDs for the sealed product(s) that this deck are associated with. 

I have a fuzzy match right now with @axxroytovu's Deck Name to yours, but it's not a perfect match. I'd like a way to either match up with Axx's Deck Name field, or you to have the UUIDs. Either approach works.

**Comment by taw** [comment]
@axxroytovu Is this done on your end?

**Comment by axxroytovu** [comment]
I believe so. If someone wants to double check, all of the decks that don't have a firm link should be:

- jumpstart deck lists
- digital only
- decks that don't have a specific product

**Comment by taw** [comment]
OK, closing it as done then.
