### ISSUE TITLE
ó character is treated case sensitive

### ISSUE THREAD

**Issue by pyyhttu** [taw/magic-search-engine#250]
If I search "lim-dul's vault" (without û) the card is returned correctly: https://mtg.wtf/card?q=lim-dul%27s%20vault

But if I search "lorien revealed" (without ó) I get nothing: https://mtg.wtf/card?q=lorien%20revealed

Searched also with "anduril" (without ú) and it does return result also correctly: https://mtg.wtf/card?q=anduril

So it seems only character "ó" is treated case sensitively, which are these: https://mtg.wtf/card?q=%C3%B3

**Comment by taw** [comment]
Yeah, I have an explicit list of Unicode characters I'm normalizing.

This isn't the cleanest solution, but they pretty much stopped using any after early years of Magic, so any accented characters were just in reprints, so it worked fine, and I never bothered implementing anything more sophisticated than that.

I added ó to the list. Let me know if I they add anything else.

**Comment by pyyhttu** [comment]
> I added ó to the list. Let me know if I they add anything else.

Inspected LotR cards through by searching  any cards with accented characters on them and they were returned correctly.

**Comment by taw** [comment]
I added proper specs for this in case they add some new characters.

There were also a lot of accented characters in artist names that I added to normalization.
