### ISSUE TITLE
Not Dead After All

### ISSUE THREAD

**Issue by pyyhttu** [taw/magic-search-engine#266]
This is minor, as I can do the search for the card with quotes and it works: https://mtg.wtf/card?q=%22not+dead+after+all%22

In Scryfall though, no quotes are needed: https://scryfall.com/search?q=not+dead&unique=cards&as=grid&order=name

**Comment by axxroytovu** [comment]
This is definitely because of how "not" is being parsed. It also breaks trying to look for "Not Forgotten", "Waste Not", and "Not of This World"

**Comment by taw** [comment]
Word "not" is treated as alias for "-" for search like it was in MCI, but I don't know if anyone actually uses this feature. Scryfall doesn't do it, and I never listed it in syntax help, so maybe I should just get rid of it.

**Comment by taw** [comment]
Changed so "not" is treated as a normal word now.
