### ISSUE TITLE
Remaining LCC / LCI issues

### ISSUE THREAD

**Issue by taw** [taw/magic-search-engine#277]
- [ ] booster packs missing
- [ ] artist information missing (mtgjson issue, not a big deal, but it gets indexer warning)
- [ ] decks have some ambiguous cards

Missing artist information:

```
No artist for Cavern of Souls ltc 392z
No artist for Bridge from Below spg 3
No artist for Kalamax, the Stormsire spg 13
```

Ambiguous cards:

```
bin/resolve_card "lcc" "Ahoy Mateys" "The Indomitable" "[LCC:43]"
bin/resolve_card "lcc" "Ahoy Mateys" "The Indomitable" "[LCC:75]"
bin/resolve_card "lcc" "Ahoy Mateys" "Storm Fleet Negotiator" "[LCC:46]"
bin/resolve_card "lcc" "Ahoy Mateys" "Storm Fleet Negotiator" "[LCC:78]"
bin/resolve_card "lcc" "Ahoy Mateys" "Francisco, Fowl Marauder" "[LCC:49]"
bin/resolve_card "lcc" "Ahoy Mateys" "Francisco, Fowl Marauder" "[LCC:81]"
bin/resolve_card "lcc" "Ahoy Mateys" "The Grim Captain's Locker" "[LCC:50]"
bin/resolve_card "lcc" "Ahoy Mateys" "The Grim Captain's Locker" "[LCC:82]"
bin/resolve_card "lcc" "Ahoy Mateys" "Skeleton Crew" "[LCC:53]"
bin/resolve_card "lcc" "Ahoy Mateys" "Skeleton Crew" "[LCC:85]"
bin/resolve_card "lcc" "Ahoy Mateys" "Broadside Bombardiers" "[LCC:54]"
bin/resolve_card "lcc" "Ahoy Mateys" "Broadside Bombardiers" "[LCC:86]"
bin/resolve_card "lcc" "Ahoy Mateys" "Gemcutter Buccaneer" "[LCC:55]"
bin/resolve_card "lcc" "Ahoy Mateys" "Gemcutter Buccaneer" "[LCC:87]"
bin/resolve_card "lcc" "Ahoy Mateys" "Arm-Mounted Anchor" "[LCC:67]"
bin/resolve_card "lcc" "Ahoy Mateys" "Arm-Mounted Anchor" "[LCC:99]"
```

**Comment by axxroytovu** [comment]
https://github.com/taw/magic-search-engine/pull/279 resolved missing booster packs with two more actions:

- [ ] Update SET booster when PLIST is updated
- [ ] Update SET booster when more information about "special guest" rates are known

**Comment by magreenblatt** [comment]
I'm having some difficulty finding the source of information for the LCI Set booster showcase/boosterfun drop rates that you've stated [here](https://github.com/taw/magic-search-engine/blob/master/data/boosters/lci-set.yaml). Can you provide any additional links or details?

From what I've been able to find so far, we lack sufficient information to accurately model the contents of the following LCI Set booster slots (see details below):

- 1 Double-faced common or uncommon -- lacking info about the drop rate of legendary showcase cards and borderless dinosaurs.
- 2 Wildcard commons, uncommons, rares, and/or mythic rares -- lacking info about the drop rate of Commander cards and borderless cards (oltec and dinosaurs).
- 1 Token, ad card, or a card from The List  - lacking info about the drop rate of Special Guests cards.

From https://magic.wizards.com/en/news/feature/collecting-the-lost-caverns-of-ixalan, we know the following about LCI Set boosters:

- Borderless cards (oltec and dinosaurs) can appear in Set boosters -- specific drop rates are unspecified.
- Commander cards can appear in Set boosters --  specific drop rates are unspecified.
- "Special Guests cards are borderless reprints of fan-favorite cards that will appear in non-foil in the slot where cards from The List can also appear in Set Boosters" -- specific drop rates are unspecified.
- "All 26 Jurassic World cards are rares within boosters and are available in 1 in 12 Set Boosters. Non-foil versions can be found replacing a common or uncommon within Set Boosters."

From https://magic.wizards.com/en/news/making-magic/set-boosters-2020-07-25, we might reasonably assume that the following still applies for LCI Set boosters:

- "Starting with Zendikar Rising [...] 1 in every 7.4 rares will be a mythic rare."
- "Slot 10 and 11 – Wildcard Rarity Slots. Rare, rare will happen 1.6% of the time." -- so odds of rare/mythic in 1 (of 2) slots is: .016 = X^2 -> X = sqrt(.016) = .12649
- "The List has commons, uncommons, rares, and mythic rares which will fall at the proper rate to one another" -- not sure what rates this means in practice, but we could assume a "normal" (e.g. Standard Draft booster) distribution.

Thanks in advance :)

**Comment by axxroytovu** [comment]
There's a lot of questions there but I'll do my best to hit all of them. Most of the rates I use are assumptions based on previous sets and then validated using a chi-square test on box opening videos to make sure they're still valid. 

Some of the key assumptions for LCI:
- Borderless and Showcase versions replace 1 of every 3 instances of a given card. 
- Commander rare/mythic cards appear at the same frequency as non-commander rares/mythics
- The showcase common/uncommon slot has each common appearing 2x as likely as each uncommon. 

I still don't have good data for the special guest drop rates so that's a complete guess.

**Comment by axxroytovu** [comment]
As for the wildcard slots, the distribution of common/uncommn/rare/mythic does match up to that listed rate.

**Comment by taw** [comment]
Are we done with LCC / LCI?

**Comment by axxroytovu** [comment]
I think so. The latest data I have is that our assumptions about the SPG rate is very close to accurate.

**Comment by taw** [comment]
OK, closing the issue then.
