### ISSUE TITLE
Rick, Steadfast Leader

### ISSUE THREAD

**Issue by pyyhttu** [taw/magic-search-engine#284]
I'm trying to query the card Rick, Steadfast Leader with: https://mtg.wtf/card?q=rick%2C+steadfast+leader but the card is not returned.

But if I query and then select its Universes Within sibling Greymond, I'm able to locate Rick: https://mtg.wtf/card/sld/143/Greymond-Avacyns-Stalwart

**Comment by taw** [comment]
Right now plan queries only check official Oracle name of the card, and [there's separate fn: operator to search "flavor name"](https://mtg.wtf/card?q=fn%3A%22Rick%2C+Steadfast+Leader%22).

This made a lot of sense back when both names were on the card, but then they did this thing where only flavor name is on the card, and Oracle name is only in Oracle, months later, so maybe it's worth changing.

**Comment by pyyhttu** [comment]
> but then they did this thing

Right. They're the one and the same card (indicated by Greymond's lower left corner marking '= SLD 143') when it comes e.g. to legend rule or getting this named by opponent's Cabal Therapy, but boy, did I need to search for this info: https://www.reddit.com/r/magicTCG/comments/16gk335/greymond_and_rick_question/

I agree with your assessment that Rick, Steadfast Leader should be returned by the query, because it's confusing if it suddenly isn't (it's like erasing history).

**Comment by taw** [comment]
[Default match changed to treat flavor name as part of the name](https://mtg.wtf/card?q=rick%2C+steadfast+leader).
