### ISSUE TITLE
Advanced sorting features

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#29]
The following features would be nice to have:

* Reversed sorting. For example, `-sort:name` for reverse alphabetical order.
* Sort by color or color identity: `sort:color` and `sort:ci`. I'd suggest the following order:
    * start with colorless,
    * then white, blue, black, red, green,
    * allied pairs (WU, UB, BR, RG, RW),
    * enemy pairs (WB, UR, BG, RW, GU),
    * shards (GWU, WUB, UBR, BRG, RGW),
    * wedges (WBG, URW, BGU, RWB, GUR),
    * 4-color (WUBR, UBRG, BRGW, RGWU, GWUB),
    * and finally WUBRG
* Sort by rarity: `sort:rare` (special, mythic, rare, uncommon, common, land)
* Multiple sort orders. For example, `sort:cmc sort:color` to sort by cmc first, and cards with the same cmc are sorted by color.

**Comment by taw** [comment]
I tried doing `sort:rarity`, it's currently working very awkwardly.

First, card selection step happens after sorting, so you'll see newer uncommon first (because old version was special rarity). This is generally OK idea, as when you're searching oldest first, showing new nicer card is usually OK, but it's silly for this. It's fixable problem.

A munch worse problem is that a lot of special rarity printings have no images, so it looks quite awful - these are mostly cards that aren't on Gatherer. For example BFZ Prerelease Drana has separate entry on mtgjson, so we have it, but not on gatherer, and I couldn't find any pic for it. This makes rarity search a nonstarter until fixed. 

The problem sets are whole http://mtg.wtf/set/rqs and part of http://mtg.wtf/set/ptc - both are marked as all rarity special.

**Comment by taw** [comment]
Sorting by reverse, color, color identity, and multiple criteria aren't usually bothered by rarity search issues, so I'll take a look at it.

**Comment by taw** [comment]
RQS problem fixed - RQS/ITP are both _almost_ 4E precons except they're listed separately as they changed copyright line by one year. So just using ITP scan for RQS (they're identical) - and changing everything's rarity from "special" to whatever they had in 4E.

That solves one minor issue, but still leaves Prerelease Events cards without scans blocking `sort:rarity`.

**Comment by taw** [comment]
So revisiting this, I wanted to add  `sort:number` (by collector number, `1`, `1A`, `2` etc.) as fairly obvious thing, but then what would it even mean to sort multiple sets.

So I tweaked it to be **set name** followed by collector number. Is set name sensible thing even?

As for other features here:

* `sort:color` `sort:ci` is sensible, would be nice to have good order of multicolored cards. I thought gold uncommons would be a hint, but actually they're all sorted alphabetically together. On the other hand Alara Reborn was totally color sorted, pretty much as you describe it (ally wubrg, enemy wubrg, shard wubrg). I guess we should follow Wizards order, even if it's weird (wubrg, multicolor ordered somehow, colorless).
* `sort:rarity` would look extremely ugly until special rarity promos cards all get pictures and `r:special` is fixed (that part is mostly done at least) - it's kinda simple feature to implement, with really awful looking result
* Reverse sort is obvious idea, not sure if there's any nice syntax for it.
* I'm not really seeing many use cases for multiple sort orders. What would be a some good examples?

**Comment by taw** [comment]
`sort:color` / `sort:ci` added now. Wedge order I used is different, as WUBRG by enemy color seemed more logical, and colorless is last as in set collector number order.

I'm wondering if we should have "land" as extra fake color going after "colorless" for purpose of this order. That's how sets are ordered after all.

**Comment by fenhl** [comment]
Colorless cards come first even in collector number order. Artifacts and lands come at the end because they're grouped separately, but I don't think we should emulate collector number order since it's inconsistent, and could be its separate thing (`sort:number`). It also makes sense for the sorting order to be continuous from fewer to more colors.

**Comment by taw** [comment]
BFZ order was:

* colorless Eldrazi
* (devoid W if there was any)
* regular W
* devoid U
* regular U
* devoid B
* regular B
* devoid R
* regular R
* devoid G
* regular G
* devoid multicolor
* regular multicolor
* colorless artifacts
* colorless nonbasic lands
* colorless basic lands

That's way too complicated order to follow.

Karn and Ugin went at start of their sets, but Ghostfire was sorted with red cards. But vast majority of colorless cards are artifacts or lands and both go on the end of each set.

It would be more logical to follow order you suggest. It just feels more natural to follow set order. Anybody else has opinion on that? I'm not super convinced either way.

**Comment by taw** [comment]
[`sort:rarity`](http://mtg.wtf/card?q=sort%3Ararity) is working, but for a lot of promos we only have fairly poor quality scans, so it's somewhat ugly.

**Comment by taw** [comment]
Reverse and multiple search orders are now working, [example](http://mtg.wtf/card?q=sort%3Apow%2C-tou%2Ccolor).
