### ISSUE TITLE
Lands are treated as colored cards

### ISSUE THREAD

**Issue by Circeus** [taw/magic-search-engine#30]
I'm not sure why, but the search engine won't return any results for "c:c t:land". what this means in practice is that excluding colorless cards from a search fails to exclude lands.

**Comment by taw** [comment]
`c:`/`c!` operators are a bit silly for reasons of compatibility with how magiccards.info did it, as people might be used to those weird rules.

`c:l` selects lands, `c:c` selects colorless non-land cards. http://mtg.wtf/help/syntax lists the rules.

I feel like leaving them be and maybe adding `c=`/`c>=`/`c<=` (and also `ci=`/`ci>=`/`ci<=`) with more straightforward semantics.

**Comment by taw** [comment]
I'll just mark it as closed unless you have any further suggestions. Compatibility syntax will probably stay, as it would confuse people, but I'd recommend most people to use the new syntax.
