### ISSUE TITLE
MKM play boosters on Arena have a couple of list swaps

### ISSUE THREAD

**Issue by fverdoja** [taw/magic-search-engine#304]
Hi,
MKM play boosters on Arena have the following swapped cards in the list slot ([source](https://magic.wizards.com/en/news/announcements/whats-new-on-the-list-for-murders-at-karlov-manor)):
> **The List in MTG Arena**
> The List is another great opportunity to bring older Magic cards to digital play. Cards from The List will appear in _MTG Arena's Play Boosters_, which are premiering with the release of Murders at Karlov Manor. We're swapping three cards from The List in tabletop—**Baleful Mastery**, **Cavalier of Thorns**, and **Death Cloud**—to introduce three new-to-MTG Arena cards instead:
> * **Possibility Storm**
> * **Evolutionary Leap**
> * **Smuggler's Copter**

Would it be possible to implement an "arena" booster for MKM as for the other sets? As far as I know that is the only change between Arena and paper for this set... except I guess that both wildcard slots are actually non-foil on arena, since arena has no foils.

Thanks!

**Comment by taw** [comment]
I did these just to make the code works, not sure how many corrections they'll need:

* https://mtg.wtf/card?q=sheet%3AMKMARENA
* https://mtg.wtf/pack/mkm-play-arena

**Comment by fverdoja** [comment]
Thanks for the first implementation.
One more note about the list (this applies to both paper and arena boosters ([source](https://magic.wizards.com/en/news/making-magic/what-are-play-boosters)):
> **Slot 7: Common/The List Card**
> 
> Most of the time (7 out of 8, or 87.5%), this slot will be a seventh common, but an eighth of the time (12.5%), you will get a card from The List. [...]
> 
> In the past, The List has mostly been reprints of older cards. Play Boosters are going to tinker with what exactly can be on The List. For example, when Play Boosters premier, The List will include what we call Special Guests, 10 cards that are exciting reprints that we can give new art and will thematically tie into whatever set they are in. What we do with the Special Guests will change set to set. (Though The Lost Caverns of Ixalan will not have Play Boosters, Special Guests is debuting with that set, so you should already have some idea of what those will look like.)
> 
> In addition to the Special Guests, there will be 40 cards that are reprints without new art. Of those, 30 will be common or uncommon and 10 will be rare or mythic rare. This is down from the 300 cards that previous iterations of The List had.
> 
> **Here's your likelihood of getting items from this slot in the first Play Booster:
>     87.5% – A common from the main set
>     9.38% – A common or uncommon normal reprint from The List
>     1.56% – A rare or mythic rare normal reprint from The List
>     1.56% – A Special Guests card from The List**

Currently the chance of a common from the main set in this slot is correct (87.5%), but otherwise all other cards are given the same chance, which is not correct.

**Comment by taw** [comment]
Is it done now? @axxroytovu

**Comment by axxroytovu** [comment]
I believe so, I haven't seen any issues so far.

**Comment by fverdoja** [comment]
At first glance it looks ok to me too. Thanks as usual.
