### ISSUE TITLE
Fallout (PIP) Collector Boosters missing

### ISSUE THREAD

**Issue by taw** [taw/magic-search-engine#307]
I think that's the only one we don't have yet.

**Comment by taw** [comment]
I had time to do draft boosters for Standard legal sets, but collector boosters are a lot more work, so I don't currently plan to do them.

Tagging @axxroytovu and @kodawah in case either of you guys is interested. If not, at least there's an issue to document this.

**Comment by kodawah** [comment]
what's the matter with pip clb?

**Comment by taw** [comment]
We just never implemented it. Right now [PIP only has precon data](https://mtg.wtf/set/pip), pip-collector is completely not implemented.

**Comment by axxroytovu** [comment]
It is on my very long list of things to do

**Comment by taw** [comment]
No pressure, I'm just documenting it in case we all forget about it.

**Comment by axxroytovu** [comment]
I have a few places that document the work to go so we aren't duplicating things:
- [The Status file](https://github.com/mtgjson/mtg-sealed-content/blob/main/status.txt) has all products that don't have contents, or products whose contents aren't linked correctly. So line 256 has `Product pip - Fallout Collector Booster Pack missing contents`
- [The Review file](https://github.com/mtgjson/mtg-sealed-content/blob/main/data/review.yaml) has all products that aren't pulled into mtgjson yet and need to be checked to see if they're valid products, duplicates of existing products, or something we don't want to track.

**Comment by axxroytovu** [comment]
Fixed in https://github.com/taw/magic-search-engine/pull/308
