### ISSUE TITLE
Whitespace is ignored for single-word search strings

### ISSUE THREAD

**Issue by Circeus** [taw/magic-search-engine#32]
I suspect this may be design choice, but I find it annoying that I can no longer (compared to magiccards.info) strictly search for "land" (i.e. while excluding "island" and "nonland") by using the search string `o:" land"`.

**Comment by taw** [comment]
Yeah, it's design decision to cleanup all input data, removing or normalizing spaces and some punctuation, replacing Unicode characters by their ASCII equivalent, lowercasing everything, stripping `'s` and plurals in many contexts, aggressively autocorrecting etc.

It usually significantly improves results.

What you're trying to do is matching word boundary not space as such. Best way to do that would probably be adding regexp search, like `re:"\bland\b"` or whatever syntax it would use.

**Comment by fenhl** [comment]
Regex search could be useful for multiple fields (name, text, flavor, etc), so I would suggest adding special syntax for it instead of a `re` prefix. For example, `name:/\bland\b/`.

**Comment by taw** [comment]
I mostly need to find some way to validate that regexp is secure so we don't just `eval` user input blindly.

The engine already turns regexps for Oracle matches internally.

**Comment by taw** [comment]
[There's now regexp search](http://mtg.wtf/card?q=o%3Aland+-o%3A%2F%5Cbland%5Cb%2F).

Currently only `o://` and `ft://` supported. I'll check which other fields could use regexps.
