### ISSUE TITLE
MOM jumpstart issue

### ISSUE THREAD

**Issue by axxroytovu** [taw/magic-search-engine#323]
From `philallen` on discord

> We got our Jumpstart boxes in and cracked them. Weirdly, there were zero Praetors in them. EV was still good ($85 per box before fees on $2+ cards). Is there a chance WotC changed the contents of Jumpstart packs midway through printing? Or are the tools just incorrect?

**Comment by taw** [comment]
Is this about "random <color> March of the Machine rare or mythic rare" slot?

I don't think WotC was ever all that specific which rares were possible there. If you feel like it's likely incorrect, feel free to change it, I have no independent information about it.

I guess there's usually youtube pack opening videos for independent check. I've done that in the past, but it's going to be quite time consuming to get decent sample there for this particular case.

In either case, I'm leaving it up to you.

**Comment by kodawah** [comment]
@axxroytovu I haven't chimed in yet, but i think it'd be better to be on the safe side and drop the preators

**Comment by taw** [comment]
This PR https://github.com/taw/magic-search-engine/pull/326 says this issue is fixed. Reopen if not so.
