### ISSUE TITLE
"bound" the search string?

### ISSUE THREAD

**Issue by Circeus** [taw/magic-search-engine#33]
Is there a way for the code to allow for restricting the search string so that nothing happens before or after it? Let's say I want cards whose rule text consists of "flying" _and nothing else_, I could search (say) `o:|flying|` (or maybe `|flying, first strike|` etc.). Or maybe I want cards with _no_ keywords, like `o:|whenever"`. Previously clever use of space in search string would allow some of it [(`o:flying -o:" "`)](http://magiccards.info/query?q=o%3Aflying+-o%3A%22+%22&v=card&s=cname), but, well... #32 kinda makes it impossible anyway.

I know the use cases are a little weird, but I'm sure people could come up with more sensible ones.

**Comment by silasary** [comment]
This seems like a good use of Regular Expressions.

**Comment by taw** [comment]
Regexp search can handle such things. It uses ruby regexp and by default uses case insensitive search to match everything else.

[`o:/\Aflying\z/`](http://localhost:3000/card?q=o%3A%2F%5CAflying%5Cz%2F)
