### ISSUE TITLE
LOTR Jumpstart Vol1

### ISSUE THREAD

**Issue by flamedemon** [taw/magic-search-engine#332]
LTR Vol1 jumpstart rares & mythics are wrong. Was previously correct but the following cards have been added and are not present in packs:
Mithril Coat
Palantir of Orthanc
The Shire
Minas Tirith
Rivendell
Sting, the Glinting Dagger
Anduril, Flame of the West
Forge Anew
Mines of Moria
Barad-dur
Hew the Entwood

**Comment by taw** [comment]
cc: @axxroytovu

**Comment by axxroytovu** [comment]
1. Taw please assign me
2. @flamedemon just checking are these the V1 or V2 jumpstart packs?

**Comment by flamedemon** [comment]
Sample size 46 boxes 
[LOTR Vol1 Jumpstart 10-15-24 - Sheet2.csv](https://github.com/user-attachments/files/17378478/LOTR.Vol1.Jumpstart.10-15-24.-.Sheet2.csv)
