### ISSUE TITLE
RVR missing foil borderless shocklands

### ISSUE THREAD

**Issue by kodawah** [taw/magic-search-engine#333]
I'm experimenting with some filtering options with ban search, and it seems like the shocklands from RVR, borderless, AND foil are not found in any product (while i believe they should appear at least in the collector boosters)

it could be a bug in my code or mtgjson script, but if someone could take a look i'd appreciate it 🙏

**Comment by kodawah** [comment]
if you want to check it out this is the search [query for RVR](https://www.mtgban.com/search?q=s%3ARVR+f%3Af+is%3Aproductless+-s%3AFDN%2CSLD%2CSLU%2CDSK%2CSPG%2CDSC%2CPCEL%2CHHO%2CDA1%2CPLST%2CMB2+-f%3Aetched++-t%3Atoken%2Cbasic+-is%3Apromo%2Coversize%2Cschinesealtart%2Cjpn+-cne%3A%5B%E2%80%A0%E2%98%85%5D%5Ba-z%5D%3F%24) 

It does seem like a lot of foils are listed in the [full query](https://www.mtgban.com/search?q=f%3Af+is%3Aproductless+-s%3AFDN%2CSLD%2CSLU%2CDSK%2CSPG%2CDSC%2CPCEL%2CHHO%2CDA1%2CPLST%2CMB2+-f%3Aetched++-t%3Atoken%2Cbasic+-is%3Apromo%2Coversize%2Cschinesealtart%2Cjpn+-cne%3A%5B%E2%80%A0%E2%98%85%5D%5Ba-z%5D%3F%24) so maybe it's a bug in the script...

**Comment by kodawah** [comment]
related to https://github.com/mtgjson/mtg-sealed-content/issues/246

**Comment by taw** [comment]
I don't have access to mtgban you linked to.

You can do queries like `booster:rvr-collector` or `booster:*`. Unfortunately they don't distinguish between foil and nonfoil. Card will match `booster:rvr-collector` if either foil or nonfoil version is available from RVR Collector's booster.

**Comment by axxroytovu** [comment]
Confirmed that bordlerless foil shocklands were improperly excluded from the showcase slot.

Also, the `count` tag not working with `use` made troubleshooting this very difficult.

**Comment by kodawah** [comment]
thanks for looking at this! will the other foil cards from the second query also be affected with the `count` fix?

**Comment by axxroytovu** [comment]
Working on it.

RVR is a mess. The "Collecting Ravnica Remastered" article says there should be 55 borderless anime cards, but scryfall only has 40 so IDK what the gap is. I think the article is just wrong.
