### ISSUE TITLE
Investigate alternatives to mtgjson

### ISSUE THREAD

**Issue by taw** [taw/magic-search-engine#34]
mtgjson has been disappointing in quality, and that version 4 is not coming.

So I started writing a simple Gatherer scrapper https://github.com/taw/magic-database

Tasks are:

- [ ] make scrapper work with split, flip, dfc, meld and other such nonstandard cards
- [ ] export all of Gatherer to json with it
- [ ] compare how many differences there are
- [ ] with different cards, compare quality
- [ ] check how many missing cards there are. By count 30911 of our cards have multiverseid, 30819 unique (duplicates presumably split cards etc.), 2213 are various mostly old promos without Gatherer ids.

After that possibilities are:

- use importer as main source, maintain promo db manually
- use importer as main source, use mtgjson as secondary source
- create some mtgjson / importer hybrid that exports to "fixed" mtgjson format
- or maybe it's all pointless

Another possibility is that with importer mtg.wtf could have spoiler cards, by just adding secondary source somehow, before Gatherer gets them.

**Comment by fenhl** [comment]
Out of curiosity, why are you creating a new database project instead of contributing to MTG JSON?

**Comment by taw** [comment]
mtgjson codebase is rather awful and devs aren't very responsive to bug reports

**Comment by taw** [comment]
Investigation so far:

* we can export something that's mostly in mtgjson format
* mtgjson contains a lot of supplemental information about sets (release dates, border colors, set type, set names in foreign languages etc.) but fairly little supplemental information about cards themselves
* mtgjson supplemental information about sets is mostly magiccards.info number (for early cards without official numbering) and starter flag (if card is in starter and not booster); I didn't notice anything else
* mtgjson also contains a lot of computed information like card layout, card color, card color identity etc. - we can compute it ourselves
* there's a lot of silly differences like Unicode quotation marks
* there's a bunch of seemingly random changes, like artist names spelling - not sure if Gatherer updated but mtgjson didn't, or Gatherer has errors and mtgjson is patching them

As far as investigation goes, I think code is currently usable backup for mtgjson in case something happens to that project.

It would probably take just as much work to get it to point where indexer can use it (split cards would be the biggest problem, it handles DFCs just fine).

I think it's OK to suspend this investigation for now.

**Comment by fenhl** [comment]
The artist name changes are most likely patches by MTG JSON. Have a look at [C.js](https://github.com/mtgjson/mtgjson/blob/master/shared/C.js#L3229), it contains all the manual patches.

**Comment by taw** [comment]
The `renumberImages` thing explains where their numbering is coming from.

They have a ton of those corrections, including things which really should be handled by rules like DFC colors.

And 133 open issues...

**Comment by taw** [comment]
So this https://github.com/mtgjson/mtgjson/issues/370 is another reason to have an alternative to mtgjson.

**Comment by broady** [comment]
scryfall is great.

I requested a bulk download like mtgjson:
https://github.com/scryfall/feedback/issues/155

**Comment by fenhl** [comment]
I would advise against Scryfall, since it is closed source.

Now that @ZeldaZach has access to the website and @gwax is doing great work fixing things, I hope that moving away from it won't be necessary.

**Comment by taw** [comment]
I made a big step of switching from single `AllSets-x.json` to using one json per set.

This makes it a lot easier to deal with mtgjson issues - it's now very easy to revert any sets that cause issues to previous version.

It has nice advantages:

* if anybody wants custom sets, they are now much easier to add - just drop one json per custom set, and indexer will handle it just fine
* if we wanted to include spoiled cards, we can just add another source for one json
* if mtgjson horribly messes up some set, and old version is outdated, it's much easier to fix just one specific file than use complex merge scripts (which I previously used)

I also cleaned up indexer source code, but it's still too messy.

**Comment by ZeldaZach** [comment]
Hey @taw If you have any suggestions or issues with JSON, please let me know via ticket on our repo and I'll be glad to help start addressing it!

**Comment by taw** [comment]
@ZeldaZach I reported https://github.com/mtgjson/mtgjson/issues/418 https://github.com/mtgjson/mtgjson/issues/419 https://github.com/mtgjson/mtgjson/issues/420

These are the only sets for which I have to use older version.

**Comment by taw** [comment]
For sake of testing I used C17 via `magic-database` as soon as Gatherer got it, and it worked just fine. It wasn't necessary this time, since mtgjson released same day anyway, but for some past sets there were problems for very long time, so it's nice to know there's a backup just in case.

**Comment by taw** [comment]
All this is probably going to be unnecessary if mtgjson4 happens sometime this year, and is something I can run locally and submit PRs to.

**Comment by ZeldaZach** [comment]
Sorry that JSON3 has been disappointing towards your project. I'm hoping to have a beta of v4 up this upcoming week with a full launch by the end of the summer

**Comment by taw** [comment]
Yeah, I can't really run the mtgjson3 locally, so I just submit issues ([and write workarounds in indexer here](https://github.com/taw/magic-search-engine/search?q=mtgjson%2Fissues&unscoped_q=mtgjson%2Fissues)), can't fix them myself.

There's no rush with all that.

**Comment by taw** [comment]
mtgjson v4 is basically fine now, so closing this backup plan.
