### ISSUE TITLE
About legalities

### ISSUE THREAD

**Issue by pyyhttu** [taw/magic-search-engine#340]
Noticed with 30th Anniversary Edition at https://mtg.wtf/card/30a/299/Armageddon as listed under Legalities being legal in all formats.

Scryfall shows the same card at https://scryfall.com/card/30a/299/armageddon as not being legal anywhere with the text:

_"This version of this card has a non-standard Magic back. It is not legal for constructed play."_

The same logic, and almost same reasoning is applied in Scryfall also to CE/IE Armageddon cards, with the text being slightly different:

_This version of this card has square edges and a non-standard Magic back. It is not legal for constructed play._ 

Proposing mtg.wtf shows and follows the same legality logic, accompanied with the above texts. Though I guess the exact text for both should be "[...]not legal for **sanctioned** play".

**Comment by taw** [comment]
Right, format legality logic is for card not for specific printing.

There are specific queries `game:paper`, `game:mtgo`, and `game:arena` to filter printings legal in each game version.

A query like `f:modern game:paper` should return exactly the right printings of the right cards.

I guess display for cards like 30A could be improved. Most other such cards say "Oversized card" or have obvious gold border, but 30A would look like regular cards at first sight.

**Comment by taw** [comment]
OK, added some warning next to legality colors.

Examples:

* [illegal paper Black Lotus](https://mtg.wtf/card/o90p/2/Black-Lotus) - warning
* [MTGO Black Lotus](https://mtg.wtf/card/prm/46932/Black-Lotus) - no warning, it's digital only, but that's a different thing
* [real Black Lotus](https://mtg.wtf/card/leb/233/Black-Lotus) - no warning
* [illegal Island](https://mtg.wtf/card/wc02/cr332/Island) - warning in slightly different wording
* [Yule Ooze](https://mtg.wtf/card/hho/11/Yule-Ooze) - no additional warning as it's not legal anywhere anyway

I don't have any cause of illegality data (oversized, gold border, nonstandard back etc.), so nothing about that.

Does it make sense?

**Comment by pyyhttu** [comment]
Yeah, the legalities with that text are more clear now.
