### ISSUE TITLE
mana={10} shows cards that cost 1

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#37]
If you search for [`mana={10}`](https://mtg.wtf/card?q=mana%3D%7B10%7D), cards that cost `{1}` are listed instead.

As a workaround, [`mana=10`](https://mtg.wtf/card?q=mana%3D10) works as expected.

**Comment by taw** [comment]
The code that made sure `{u/w}` and `{w/u}` are treaded as same thing decided that `{10}` is same as `{01}` too.

It's fixed now.
