### ISSUE TITLE
Missing symbols

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#38]
The following symbols seem to be missing and are rendered as text instead:

* `{CHAOS}` (plane cards)
* `{P}` ([Rage Extractor](https://mtg.wtf/card/nph/91))
* `{PW}` (rulings of plane cards)
* Level symbols (cards with level up)
* Loyalty costs (planeswalkers)

**Comment by taw** [comment]
Yeah, it's whatever we have in the sheet.

I think there are some better symbol sheets somewhere.

Level symbols and loyalty costs aren't tagged in sources, but it's probably just a regexp.

**Comment by fenhl** [comment]
While we're looking for a new symbol sheet, we might also want to add Hi-DPI versions of the symbols. The current ones look pretty bad on my screen.

**Comment by taw** [comment]
[Probably this one](https://www.slightlymagic.net/forum/viewtopic.php?f=15&t=4430) for just HQ symbols.

[There are also some fonts](https://github.com/andrewgioia/Mana).

**Comment by fenhl** [comment]
Level symbol keyword abilities should be parseable with a regex, yes.

For loyalty symbols, I have opened mtgjson/mtgjson#397 to make parsing them easier.

The font seems [easy enough](https://andrewgioia.github.io/Mana/attributes.html) to use.

**Comment by taw** [comment]
Font is easy to use, but I don't know how to edit it if something needs changing, so I don't feel super comfortable relying on it. I'll take a look, otherwise I'll just get higher res image sheet.

**Comment by fenhl** [comment]
I can only say that the maintainer of that font has been super quick to respond to any issues (including feature requests) the MTG wiki team had regarding [the set symbol font](https://github.com/andrewgioia/Keyrune).

**Comment by taw** [comment]
I tried Goblin Hero's set, but it lacks colorless and energy symbols, which is a bigger problem than having Z, unsymbols, and higher res. So that one is unfortunately not viable.

**Comment by taw** [comment]
OK, mtg.wtf now uses mana font: [P](https://mtg.wtf/card/nph/91), [HW](https://mtg.wtf/card/uh/16/Little-Girl), [XYZ](https://mtg.wtf/card/ug/53/The-Ultimate-Nightmare-of-Wizards-of-the-Coast-Customer-Service), [CHAOS](https://mtg.wtf/card/pca/1009/Academy-at-Tolaria-West), [high res hybrid](https://mtg.wtf/card/shm/226/Elvish-Hexhunter) etc.

Loyalty / level up currently not represented, as data we're getting from mtgjson does't use them.

**Comment by taw** [comment]
There's are the question of finer points of typography - like on cards tap symbol is a bit smaller than mana symbols etc. I think we don't really need to worry about that at least.

**Comment by fenhl** [comment]
The `{P}` on Rage Extractor isn't supposed to have a circle around it.

**Comment by taw** [comment]
Is there some logic behind it? It feels weird for one mana symbol without circle around it.

**Comment by taw** [comment]
OK, comprehensive rules explicitly say it's not supposed to have a background, fixed now.

**Comment by fenhl** [comment]
It's not really a mana symbol, but rather a placeholder that represents any of the 5 Phyrexian mana symbols.

Also, `{CHAOS}` isn't a mana symbol at all and isn't supposed to have a circle either.

**Comment by taw** [comment]
`{CHAOS}`, `{PW}` (in Comprehensive Rules only), and `{E}` don't have mana circles either now.

That should be all of them. `{S}` seems to have very faint circle on cards, so kept.

There's also a thing that mana costs have circle shadows when in card top bar, but not in card text. Should we do that too?

**Comment by fenhl** [comment]
Personally I think the mana symbols are more readable without the drop shadow.

**Comment by taw** [comment]
Closing this. Possible future improvements moved to https://github.com/taw/magic-search-engine/issues/39 and https://github.com/taw/magic-search-engine/issues/40
