### ISSUE TITLE
Increase gap between abilities

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#42]
Currently, the paragraph break between abilities has the same height as line breaks within an ability. It would be useful to be able to tell where an ability ends and the next begins in a card's Oracle text.

**Comment by taw** [comment]
25% gap for every explicit line break, which approximately matches typography on Magic cards.

Of course we could make it look more like a Magic card by using serif fonts, slightly lower line height etc. Not sure here's much value in it.

**Comment by fenhl** [comment]
I'm not seeing any difference.

**Comment by taw** [comment]
[Check this](http://mtg.wtf/card/soi/49a/Aberrant-Researcher).

It's same gap between abilities as between abilities and flavor text.

Within ability or within flavor text line height is smaller.

(tested on OSX Chrome)

**Comment by fenhl** [comment]
I can confirm that it works in Chrome. For some reason, it doesn't work in Safari.

**Comment by taw** [comment]
Oh, OK, I can use some different CSS to achieve this effect.

**Comment by taw** [comment]
New CSS should work in both browsers.

**Comment by fenhl** [comment]
It does!
