### ISSUE TITLE
Rules page jumps to top after using section link

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#43]
Clicking an anchor link to a section or rule on the rules page seems to trigger some sort of JS reload in addition to the anchor jump. The result is that the page scrolls up to the very top.

**Comment by taw** [comment]
Side effect of Rails 5 update. It enables turbolinks which apparently has outstanding issue with this https://github.com/turbolinks/turbolinks/issues/105

It can be fixed by disabling turbolinks. Just checking if there's any middle way.

**Comment by taw** [comment]
Or https://github.com/turbolinks/turbolinks/issues/75 etc. It seems everybody has this problem.

**Comment by taw** [comment]
Fixed now by disabling turbolinks.

**Comment by taw** [comment]
Reenabled turbolinks except on rules page. I think this covers all cases, but I could be missing something.

**Comment by fenhl** [comment]
This issue seems to have come back at some point.

**Comment by taw** [comment]
That looks like a different issue.

When I click on section links on rules page it works, but when I refresh the rules page (with `#section` in the url) it works, but then it focuses on search bar.

So the solution is to avoid autofocus on search bar on rules page.

**Comment by taw** [comment]
This should be fixed now.
