### ISSUE TITLE
There are queries which are difficult to express

### ISSUE THREAD

**Issue by taw** [taw/magic-search-engine#45]
Some things I wanted to do:

- [x] `r>=rare` - currently needs `(r:rare or r:mythic)` (what about `r:special` ?)
- [x] some way to express Standard-legal printings - is `(st:core or st:ex)` even right?
- [x] cards released on specific date - `print:"2015-07-17"` works, but requires quotes, `print:2015-07-17` silently does `print:2015 not 07 not 17`
- [x] cards related to some other cards needs `related:t:*` since `t:*` matches everything. 
- [x] hybrid mana in Oracle text - in most other contexts `{u/g}` and `{g/u}` both work, but for `o:` queries order needs to be specific
- [ ] all queries about what's a reprint - simple queries don't work due to noise from promos, Duel Decks etc.
- [x] cards which are in two sets, like `e:m10 alt:e:m11` - all operators like `alt:` are rather dubious, `//` is the only really intuitive one
- [x] example of failed query I tried - ~~`f:standard (r:rare or r:mythic) sort:new (st:core or st:ex) alt:(st:core or st:ex)`~~ - now `f:standard r>=rare sort:new st:std alt:(st:std)`

**Comment by fenhl** [comment]
Special should be considered rarer than mythic, and basic land rarity should be considered less rare than common.

**Comment by taw** [comment]
Usually yes, but `r:special` has been a dumping ground for anything that doesn't fit the usual rarity system.

For example mtgjson has these two 4E precons as all-special - [ITP](http://mtg.wtf/set/itp) [RQS](http://mtg.wtf/set/rqs).

There's also reverse case - [like these should probably all be `r:special`](http://mtg.wtf/card?q=is%3Apromo+-r%3Aspecial+)

**Comment by fenhl** [comment]
I would argue that both of these are bugs in MTG JSON.

**Comment by fenhl** [comment]
I realize that you have already reported the first one. For reference, it is mtgjson/mtgjson#422.

**Comment by taw** [comment]
Yeah after https://github.com/taw/magic-search-engine/issues/29 I tried doing sort by rarity, but `r:special` was messy.

Another one I just noticed, [CSTD](http://mtg.wtf/set/cstd) probably shouldn't be all-special.

Not sure about [AT](http://mtg.wtf/set/at) either.

**Comment by taw** [comment]
`r>=rare` is done. https://github.com/taw/magic-search-engine/issues/48 for some followup issues with it.

**Comment by taw** [comment]
Reliable `is:reprint` queries aren't really happening, as mtgjson v4 only has per-set release date, and promo sets will mess it up.

**Comment by taw** [comment]
Closing as everything here is done except for reprint queries, which probably won't happen.
