### ISSUE TITLE
Schemes, Vanguards, Planes, and Conspiracies all live in the Command Zone, and are not permanents.

### ISSUE THREAD

**Issue by silasary** [taw/magic-search-engine#47]
[is:permanent (-t:creature -t:enchantment -t:artifact -t:land -t:planeswalker -t:Eaturecray)](http://mtg.wtf/card?q=is%3Apermanent+%28-t%3Acreature+-t%3Aenchantment+-t%3Aartifact+-t%3Aland+-t%3Aplaneswalker+-t%3AEaturecray%29)

**Comment by taw** [comment]
Well, a creature card is sometimes a "spell" (on stack), sometimes a permanent (on battlefield), sometimes neither (anywhere else).

But people also use "spell" to mean "instant or sorcery", and "permanent" to mean "everything except instant/sorcery".

Is there any good name for `t:scheme or t:conspiracy or t:vanguard or t:plane or t:phenomenon` ? If we have a good name I'm fine with making this a third category.

(your query currently misses up a few Unglued cards, but they're supposedly getting Oracle update when next unset comes up)

**Comment by fenhl** [comment]
CR 110.4a defines a permanent card as “an artifact, creature, enchantment, land, or planeswalker card”.

My suggestion for cards that are neither permanents nor instants or sorceries would be “supplemental”.

**Comment by taw** [comment]
Good point on 110.4a.

Not really fan of "supplemental" name.

**Comment by taw** [comment]
Actually I completely misremembered `is:spell` matches everything except lands. Both meanings copied straight from magiccards.info

**Comment by taw** [comment]
`is:permanent` is fixed.

It's a separate followup issue what `is:spell` should mean, and if there ought to be a query for Command Zone cards.
