### ISSUE TITLE
Flipped flip cards should not have a nonzero mana cost

### ISSUE THREAD

**Issue by Ketsuban** [taw/magic-search-engine#5]
I want a list of things I can use as my commander. `(t:Legendary t:Creature OR o:"can be your commander") mana>0` should do that, but apparently Autumn-Tail, Kitsune Sage is treated as having the same mana cost as Kitsune Mystic when that's not the case.

**Comment by taw** [comment]
I'm not sure if this is the most helpful result, but it's technically correct.

[Rule 709.1c for flip cards says](http://mtg.wtf/help/rules#section-709-1c):

> _A flip card’s color and mana cost don’t change if the permanent is flipped. Also, any changes to it by external effects will still apply._

[Gatherer](http://gatherer.wizards.com/Pages/Search/Default.aspx?name=+[kitsune]+[sage]) behaves the same way as well.

This is [different from DFC cards's rule 711.4b](http://mtg.wtf/help/rules#section-711-4b):

> _While a double-faced permanent’s back face is up, it has only the characteristics of its back face. However, its converted mana cost is calculated using the mana cost of its front face. This is a change from previous rules. If a permanent is copying the back face of a double-faced card (even if the card representing that copy is itself a double-faced card), the converted mana cost of that permanent is 0._

[mtg.wtf even follows 711.4b](http://mtg.wtf/card?q=t%3Aplaneswalker+cmc%3D2) while Gatherer doesn't.

**Comment by Ketsuban** [comment]
Alright. It would be convenient to have a way to filter out back faces and flipped cards for the purposes of the search I mentioned.

**Comment by taw** [comment]
Both [`is:primary`](http://mtg.wtf/card?q=is%3Aprimary+layout%3Ameld) and [`is:commander`](http://mtg.wtf/card?q=t%3Alegendary+-is%3Acommander) are now implemented.
