### ISSUE TITLE
Information about Vanguard MTGO-only cards is messed up

### ISSUE THREAD

**Issue by taw** [taw/magic-search-engine#50]
As far as I can tell, Gatherer is wrong, and mtgjson is wrong (in a different way).

Here's example on just one of avatars:

* [Gatherer 1](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=214824) [Gatherer 2](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=182291) - same art, says "alt art", both artist UDON
* [mtgjson 1](http://mtg.wtf/card/van/73/Birds-of-Paradise-Avatar) [mtgjson 2](http://mtg.wtf/card/van/112/Birds-of-Paradise-Avatar) - says artist one is UDON, other is Marcelo Vignali
* [deckmaster 1](https://deckmaster.info/card.php?multiverseid=182291) [deckmaster 2](https://deckmaster.info/card.php?multiverseid=214824)

[wiki says there were only 32 printed](https://mtg.gamepedia.com/Vanguard), rest is MTGO-only. That agrees with scan source.

Here's another one:
* [1](http://mtg.wtf/card/van/86/Grinning-Demon-Avatar) [2](http://mtg.wtf/card/van/110/Grinning-Demon-Avatar) - different art, but on-picture credit is UDON, but mtgjson credit is different

No idea what to do with those MTGO-only cards. Right now we have correct Oracle text, but "printings" are all messed up, and I'm not sure what's the one true source of information here.

**Comment by silasary** [comment]
UDON refers to [UDON Entertainment](https://udoncrew.deviantart.com/).

Individual artist credits can be sourced from their individual DeviantArt posts.

eg: https://udoncrew.deviantart.com/art/MtG-Online-Braids-131712029  (Alas, not all of them appear to be listed on DeviantArt)

**Comment by silasary** [comment]
While UDON is technically correct, getting the proper artists credited would be better.

The credit to Mark Zug on 86 is however very likely wrong.

**Comment by taw** [comment]
[Marcelo Vignali](http://mtg.wtf/card?q=a%3A%22marcelo+vignali%22) is one of their regular artists and [this is just card art](https://deckmaster.info/card.php?multiverseid=214824), so I doubt UDON is 
 correct in any way.

I only checked a few random avatars. Right now I'm not even sure what's the one source of truth.
Does MTGO include all the "scans" somehow?

**Comment by silasary** [comment]
UDON is responsible for at least 17 of the avatars (Unfortunately listed in the generic [Fantasy](https://udoncrew.deviantart.com/gallery/4349804/Fantasy) section of their gallery).

Magic Online no longer has useful scans for the avatars, as it constructs the data from the same faulty dataset as Gatherer.

Interestingly, it doesn't even appear to have that printing of Birds, so I have no clue where that came from 😒 

![image](https://user-images.githubusercontent.com/194254/30251020-4c5ab682-969b-11e7-9df0-57d6d7b90b8e.png)

**Comment by taw** [comment]
I'm not even totally sure if we should even include MTGO-only nonstandard cards, especially with such data quality issues. mtgjson has Vanguard avatars, but not for example [Gleemox or Library of Congress](https://mtg.gamepedia.com/Magic_Online#Cards), and right now we just follow whatever mtgjson does.

**Comment by silasary** [comment]
I am in the process of getting Gleemox added (just having issues wrangling mtgjson into building on my windows machine).

As for Library of Congress...
![avatar - congress](https://user-images.githubusercontent.com/194254/30251116-0b42395c-969d-11e7-8f6b-2c9f5faa64c2.PNG)

It's an avatar now.

With that said, Freeform Vanguard is still a playable format on MTGO, and those cards are therefore useful and playable.  I'd vote for keeping them in.

**Comment by taw** [comment]
[Those scans look nice](https://deckmaster.info/set.php?shortcode=VAN). 116 of them vs 106 is mtgjson [???].

No idea where they got them from.

**Comment by silasary** [comment]
They look like MTGO v3 scans.  (Mine come from v4)

**Comment by taw** [comment]
Any idea why [this](http://gatherer.wizards.com/Pages/Search/Default.aspx?action=advanced&type=+[%22Vanguard%22]) returns zero results?

**Comment by silasary** [comment]
You're missing the [special=true](http://gatherer.wizards.com/Pages/Search/Default.aspx?action=advanced&type=+[%22Vanguard%22]&special=true)

**Comment by taw** [comment]
mtgjson v4 killed this problem by killing VAN and replacing it with different sets (MOA, PVAN) with new images. Not sure if they're great, but I doubt any of this applies anymore.
