### ISSUE TITLE
Expose format history / banlist changes in UI

### ISSUE THREAD

**Issue by taw** [taw/magic-search-engine#52]
We have better banlist history information than anybody else, so it's a shame that it's burried deep in the code and only accessible via `time:`.

It would be nice to create interface for that.

**Comment by taw** [comment]
The interface is extremely rudimentary, but at least people can view it.

Examples:

* http://mtg.wtf/format/commander
* http://mtg.wtf/format/standard
* http://mtg.wtf/format/mirrodin-block

Super early times not really accurate. Also not even trying Penny Dreadful.

Another mystery is format history other than banlist changes - events as printings, rotations, other changes (Portal legalization)

**Comment by silasary** [comment]
Historical Penny Dreadful data would be relatively easy, should you wish to implement it.

Seasons of PD align directly with Standard rotations, and are stored at [http://pdmtgo.com/SETCODE_legal_cards.txt](http://pdmtgo.com/AKH_legal_cards.txt), where SETCODE was the latest standard set release. (For example, AKH_legal_cards.txt represents the legal set for the time between the release of Amonkhet and the release of Hour of Devastation)

Historic records are available from the start of the format with EMN, all the way to present day.

With that said, they are considered rotations, not (un)bannings.

**Comment by taw** [comment]
I don't expect too many people to be interested in historical Penny Dreadful format.

Displaying what rotated in/out of Standard when might be more useful.

**Comment by taw** [comment]
No idea why I have 1996/1999 Commander banlist changes. Maybe I should have kept better notes back when I was doing the research.

In any case, this is done now, even if UI is kinda dubious.
