### ISSUE TITLE
Preconstructed deck lists

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#53]
The help channel [#mtgrules](irc://efnet.port80.se/#mtgrules) just got a question about which cards from the C13 precon [_Nature of the Beast_](https://mtg.gamepedia.com/Nature_of_the_Beast) are legal in Modern. Answering this question was possible by jumping through some hoops, but this could be improved: I would like to request a parameter `deck:` which would filter by cards (or, more correctly, printings) that appeared in that deck. The data for these deck lists can be obtained from the wiki, for example. With this feature, the question could be answered using the query `deck:"Nature of the Beast" f:Modern`.

**Comment by fenhl** [comment]
I could aggregate the data for these deck lists as an MTG JSON extension.

**Comment by taw** [comment]
Yeah, it sounds useful, and it's a nice weekend project to scrap all lists.

[There's been quite a few decks](https://en.wikipedia.org/wiki/List_of_Magic:_The_Gathering_theme_decks).

[I wrote scripts for scrapping decklist data from Wizards site](http://github.com/taw/mtg), which could make it a lot faster - but it's been a while since I last used them.

**Comment by fenhl** [comment]
In case anyone is curious, here's how I answered the question without this feature:

1. Open [the edit page](https://mtg.gamepedia.com/Nature_of_the_Beast?action=edit) for the wiki article
2. Remove the section headers from the decklist
3. Copy the decklist to the clipboard
4. Run the script `pbpaste | perl -pe 's/[0-9]+ (.+?)\n/ or name="$1"/g' | perl -pe 's/$/)\n/' | perl -pe 's/^ or /(/'`
5. Paste the resulting query into mtg.wtf and add `f:Modern`
6. Shorten the results page's URL using http://tinyurl.com/ to avoid IRC's message size limit (other URL shorteners including 4.ly, bit.ly, and goo.gl rejected the URL for being too long)

**Comment by taw** [comment]
Wiki has download links for decklists, that could save you one step.

**Comment by taw** [comment]
I'd redirect further discussion to this new repo: https://github.com/taw/magic-preconstructed-decks/issues/1

**Comment by taw** [comment]
[All precons are now on the site](http://mtg.wtf/deck). http://mtg.wtf/deck/c13/nature-of-the-beast etc.

Search is not implemented yet, I mostly need to figure out how to deal with decks having same name. For example there's been quite a few decks called "Goblins". (also one "Goblin" which seems like an error).

I could just match them all. `e:"Merfolk vs. Goblins" deck:"Goblins"` or `e:rix deck:Angrath` is reasonable enough UI.

There's one additional problem that currently decklists just pick one arbitrary printing when multiple are available. So the search engine thinks only 1/3 C17 Forests actually exist.

**Comment by taw** [comment]
[`deck:"Nature of the Beast" f:Modern` query totally works now](http://mtg.wtf/card?q=deck%3A%22Nature+of+the+Beast%22+f%3AModern)

I'm sure there are some issues with the system, they should go into separate tickets.

In perfect world, this information should probably move to mtgjson, but it's hard to get them to fix typos, so for time being I'll maintain it as part of https://github.com/taw/magic-preconstructed-decks

**Comment by fenhl** [comment]
We're rewriting MTG JSON in Python now. If you'd like to contribute or just give suggestions, feel free to join us on Discord: https://discord.gg/74GUQDE

**Comment by taw** [comment]
I'll drop by for a chat. Realistically I have so many unfinished projects and so little time, I won't be able to contribute much. This one was about one day to finish, but it waited half a year for that one free day.

It would be nice if at some point someone took over maintaining precon database and integrated it into new mtgjson, but it's a fairly easy project to run at this point.

Or even better if someone tagged what's foil and what's not, but that's a lot of decks to tag. (it's one of many prerequisites for `is:foil` / `is:nonfoil` search).
