### ISSUE TITLE
playable:modern

### ISSUE THREAD

**Issue by taw** [taw/magic-search-engine#54]
It's not totally clear how to achieve that (fetch top-8 decks from wizards.com etc.), and what would be the threshold, but I wanted this feature a lot of times to just filter the relevant cards.

**Comment by taw** [comment]
I have no idea how to realistically implement this.

**Comment by glaebhoerl** [comment]
I was briefly curious and found https://github.com/gabriel-ballesteros/mtg-metagame-scraper and https://mtgmeta.io/docs fwiw (if you hadn't already been aware of them).

**Comment by taw** [comment]
Thanks. I might take a look at it someday.
