### ISSUE TITLE
Short rarity query

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#55]
There are only 6 possible rarities in MTG JSON: Common, Uncommon, Rare, Mythic Rare, Special, and Basic Land. It would make sense to have abbreviations for the rarity filters, for example:

* `r:L` (Basic Land)
* `r:C` (Common)
* `r:U` (Uncommon)
* `r:R` (Rare)
* `r:M` (Mythic Rare)
* `r:S` (Special)
    * possibly with `r:P` as an alias for `r:S` (used on the M15 frame for promo cards)

**Comment by taw** [comment]
Yeah, it makes sense to have shortcuts. And common/uncommon/rare/mythic make sense.

After that problems begin:

* `r:special` is sort of fake rarity for everything that doesn't fit. [I manually fixed 173 `r:special` cards already](http://mtg.wtf/card?q=e%3Acstd%2Crqs%2Citp+%2B%2B).
* `r:basic` is a bit fake - for some reason [promo basic lands](http://mtg.wtf/card?q=r%3Abasic+st%3Apromo+%2B%2B+sort%3Anew) are r:basic even when they clearly have rare symbol. They should probably all be `r:special`.
* Gatherer has 8 rarities: 4 + special, promo, land, and bonus.
* Gatherer [land being different than our basic](http://gatherer.wizards.com/Pages/Search/Default.aspx?action=advanced&special=true&rarity=+[L]). It's closer to "whatever goes onto basic land sheet" - so basic snow-covered lands (which go onto common sheet) aren't there, but Urza lands (presumably on basic land sheet) are. Should we follow Gatherer here?
* [Gatherer promo is just one card.](http://gatherer.wizards.com/Pages/Search/Default.aspx?action=advanced&special=true&rarity=+[P]) - some leftover ?
* [Gatherer bonus is just 9 cards](http://gatherer.wizards.com/Pages/Search/Default.aspx?action=advanced&special=true&rarity=+[B]) - [at least it makes sense here](http://mtg.wtf/card?q=e%3Avma+r%3Aspecial)
* [Gatherer special is mostly special](http://gatherer.wizards.com/Pages/Search/Default.aspx?action=advanced&special=true&rarity=+[S])
* And Gatherer doesn't even cover most promos.

[Some sources about sheets](https://mtg.gamepedia.com/Print_sheet).

Not sure if it's worth using this to fix rarity system.

**Comment by taw** [comment]
One letter aliases now supported, and promo basics moved to `r:special` [ https://github.com/mtgjson/mtgjson/issues/462 ].

I feel basic/special rarities are still a bit awkward, but not sure what else can be fixed.

**Comment by fenhl** [comment]
Most of these problems are actually just bugs in MTG JSON. For example, the Basic Land rarity in MTG JSON is supposed to be equivalent to Gatherer's land rarity.

I feel like this can be closed, since incorrect rarities are really their own issue.

**Comment by taw** [comment]
Yeah, closing this.
