### ISSUE TITLE
Masters Edition scans

### ISSUE THREAD

**Issue by taw** [taw/magic-search-engine#59]
Gatherer doesn't show any pics for them. [Like this](http://gatherer.wizards.com/Pages/Card/Details.aspx?printed=true&multiverseid=184587)

MCI/scryfall have new pics. [Like this](https://magiccards.info/me2/en/7.html). Are they "real", or they made them up?

[Especially stuff like this dual land seems fake](https://magiccards.info/me2/en/238.html). [Here's scryfall](https://scryfall.com/card/me2/238).

The whole idea of canonical scans of MTGO-only digital cards is annoying. Anybody has any idea?

**Comment by fenhl** [comment]
MCI's Masters Edition renders are made up. The watermarks on the dual lands are unofficial hybrid mana symbols made by someone in the Custom Magic community.

I'm not sure where Scryfall got its render. The current MTGO client doesn't show reminder text as far as I know.

**Comment by taw** [comment]
Does current MTGO client show those cards as they are on Gatherer, except with updated Oracle text?

**Comment by fenhl** [comment]
I don't have access to MTGO myself, I just remember the no reminder text bit from a similar discussion relating to *Vintage Masters*.

**Comment by fenhl** [comment]
Here's a screenshot of a *Masters Edition 2* Badlands, taken in February:

![*Masters Edition 2* Badlands](https://user-images.githubusercontent.com/641386/31631418-31a584f0-b2a9-11e7-9918-289c1d55291e.png)

**Comment by taw** [comment]
Right. I wonder if it's worth it creating renders. Or just reusing someone else's renders. Or screenshotting MTGO.

I even pondered adding option to replace all scans with Oracle-updated renders which would otherwise look the same, but that might be a lot of work.

**Comment by silasary** [comment]
Note that MTGO has three different modes for when it renders cards.

- In Duel
- In Collection (above)
- Zoomed/Preview Window (below)

![30298](https://user-images.githubusercontent.com/194254/31661639-2ae24c3c-b387-11e7-8172-546558f8f190.png)

**Comment by taw** [comment]
So I thought scryfall just screencaped MTGO zoom window, but apparently their render is different. Does MTGO render changes when you make it bigger? Or is it completely made up by them?

![me2-225-badlands](https://user-images.githubusercontent.com/17444/31661994-a6efc6b8-b334-11e7-9f38-7e3d48445b76.jpg)

**Comment by taw** [comment]
Closing it as really low priority.
