### ISSUE TITLE
Allow searching by foreign name

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#6]
It would be helpful if searching by name also worked for non-English card names, or if there were a special syntax for this.

**Comment by taw** [comment]
It definitely shouldn't be default, getting rid of pollution by non-English names [was one of the big reasons I wrote mtg.wtf in the first place](http://t-a-w.blogspot.com/2013/07/how-to-make-magiccardsinfo-even-better.html).

As for special fields with query like `ru:Голем`, I tried implementing just that, but I ran into a weird problem that names change from printing to printing. For example Thran Golem in Russian:

* [Голем Трана](http://gatherer.wizards.com/Pages/Card/Languages.aspx?multiverseid=83202)
* [Транский Голем](http://gatherer.wizards.com/Pages/Card/Languages.aspx?multiverseid=234072)

It's basically a question of treating it as per-card property (and in such case, does it have two names, most recent name only, or how does that work exactly?) or per-printing property (which would be somewhat weird).

There's also minor issues:

* unicode - right now we force everything to ascii to save people [from weirdness like this](http://mtg.wtf/card/tsts/19) (also from AE ligature before Oracle got rid of that too). It wouldn't affect Russian/Chinese/Japanese as they use completely separate character sets, but no idea about German, French, Italian etc.
* do we want to display those foreign names somewhere? If so, do we normalize per-card, per-printing, or how?

**Comment by fenhl** [comment]
Normalizing everything to ASCII is a bad idea (in some languages, there are minimal pairs where the word means something else depending without the diacritics).

If someone's searching for e.g. the German version of [Anger](https://mtg.wtf/card/ju/77), you'll want to accept both normalized (`de:Arger` or `de:Aerger`) and exact (`de:Ärger`) queries, to accomodate both someone who has gotten their hands on a German card (and may not be able to type the diacritics on their keyboard) and native German speakers.

**Comment by taw** [comment]
We could figure out some special case for German umlauts, force normalizing everything is pretty much best strategy for English, but I'm aware it's less great for other languages.

I'll probably just add some rudimentary support for queries like `de:*` soon, and leave more complex issues like name changes between printing and umlauts for later.

**Comment by taw** [comment]
It's working now (disregarding edge cases) - http://mtg.wtf/help/syntax for some examples
