### ISSUE TITLE
Ability words should be in italics

### ISSUE THREAD

**Issue by taw** [taw/magic-search-engine#60]
[Like here](http://mtg.wtf/card?q=o%3Adomain). Every "Domain —" etc.

[Comprehensive Rules](http://mtg.wtf/help/rules#section-207-2c) have full list.

mtgjson doesn't indicate them, so it needs to be a regexp, either at indexing time or display time.

**Comment by taw** [comment]
[Not everything with long dash needs it](http://mtg.wtf/card?q=o%3A%22%E2%80%94%22).

"Cumulative upkeep—", "Choose one —" etc. shouldn't use italics.

**Comment by fenhl** [comment]
Related upstream issue: mtgjson/mtgjson#75. Probably isn't going to get fixed any time soon, so it makes sense to fix here.

We could parse CR 207.2c, which contains the complete list of ability words.

**Comment by taw** [comment]
Yeah, I'm thinking regexping it display time, as currently rules text is saved as plaintext, not html/markdown/etc.

**Comment by taw** [comment]
[It works now](http://mtg.wtf/card?q=o%3A%E2%80%94).

[For the regexp used](https://github.com/taw/magic-search-engine/commit/174a000d1ffe2440b6af6be1ec7e8492bbd1c3d8) - new ability words will have to be added manually, but test will fail if that ever happens.

We shouldn't really just parse CR as they get updated weeks after set release.

**Comment by fenhl** [comment]
CR are updated on set release. They haven't been delayed since Eli Shiffrin took over.

**Comment by taw** [comment]
They're never ready same day as Gatherer, which is what we want. Looking at git log dates, Ixalan update was on Gatherer Sep 19, CR update was Sep 28.

As regexp for new ability word needs to be ready same time as cards with it appear in the database, it's still better to do it manually (to be fair, cost of waiting is just lack of italics for a while).

I'm also pretty sure in the past it sometimes took quite way longer than just extra ~10 days.
