### ISSUE TITLE
time:MRD produces warning

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#63]
[`time:MRD f:Standard`](https://mtg.wtf/card?q=time%3AMRD+f%3AStandard) produces the following warning below the search box, but then also gives the correct results:

```
Doesn't look like correct date, ignored: "mrd"
```

[`time:mi f:Standard`](https://mtg.wtf/card?q=time%3Ami+f%3AStandard) works fine.

**Comment by taw** [comment]
Right, `time:mrd f:standard` actually does two things. Limits cards which existed by the time mrd got released, and limits cards to mrd-Standard.

For silly reasons of avoiding circular dependency (query parser doesn't have access to database), `time:` resolution for set names gets delayed until query gets run, and those two sub-queries do it separately, in different ways.

This isn't the greatest approach, and I fixed this specific issue, but moving date resolution somewhere else would probably be a good idea.
