### ISSUE TITLE
"c:"+letter of color+more letters

### ISSUE THREAD

**Issue by cftsoc3** [taw/magic-search-engine#68]
Search engine seems to be treating the rest of the letters as a separate token rather than throwing an error. Additionally if the next letters are valid ORs for "c:" it will add until it hits one that is invalid. e.g. discovered while attempting to search "c:black" before fully understanding the syntax; produces equivalent of "c:bl ack".

**Comment by taw** [comment]
Query parser tries its best to do something useful with query that's not quite correct.

Sometimes its best is not that great.

One big issue with current design is that all `x:y` / `x=y` operators work _almost_ the same, but not completely so, this being an example.

**Comment by taw** [comment]
I fixed color operators (`c:`, 'c!`, `c>=`, `ci:`, `in:` etc.) to give warning when they don't recognize something, and special cased 5 color names to work.

[Example](http://mtg.wtf/card?q=in%3Ablack)

That should be good enough.
