### ISSUE TITLE
mana>={M/N}

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#69]
To search for hybrid mana, equivalent to `mana>={H}`. This would also allow things like `mana>={W/M}` to search for hybrid mana where one of the two colors is white, or `mana>={2/M}` to search for twobrid.

**Comment by taw** [comment]
I agree it would be a nice feature.

`ConditionMana#resolve_variable_mana` is already pretty complicated, I wonder if it wouldn't be easier to just try all 5\*4\*3\*2\*1 permutations.

**Comment by fenhl** [comment]
Relatedly, `mana>={M/P}` for Phyrexian mana.

**Comment by taw** [comment]
For sure, it would be a very good idea, it's a bit nontrivial to implement.

**Comment by taw** [comment]
Another thing would be one extra variable to search for 4-color cards, like `mana={m}{n}{o}{p}`, except `{p}` is already Phyrexian mana.

Maybe something like `ci=4` or `c=4`  for 4-colored cards. Then `c:m` is `c>1` etc. We're not doing anything else with numbers in color expressions.

**Comment by taw** [comment]
OK, at least this is working now - [`c<=1 ci=5`](http://mtg.wtf/card?q=c%3D1+ci%3D5).

**Comment by taw** [comment]
Closing long inactive feature requests. Feel free to reopen if still interested.
