### ISSUE TITLE
Accept language codes printed on cards

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#7]
Follow-up to #6: Simplified Chinese should be searchable by `cs:巨龙`, and Traditional Chinese should be searchable with `ct:巨龍`, since these are the language codes printed on the M15 card frame.

**Comment by taw** [comment]
Names I use are what MCI seems to be using, there seems to be no standard whatsoever. [ISO uses `zh-s` and `zh-t` apparently](https://en.wikipedia.org/wiki/Template:ISO_639_name), but I don't want names like that here.

**Comment by fenhl** [comment]
Supporting both is always an option.

**Comment by taw** [comment]
Supporting both is probably the easiest solution.

**Comment by taw** [comment]
It now supports both `tw:/cn:` and `ct:/cs:` conventions.
