### ISSUE TITLE
Untap symbol styled incorrectly

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#79]
The untap symbol, as seen on [16 cards and one un-card](http://mtg.wtf/card?q=o%3A%7BQ%7D) should be a white arrow in a black circle. It is currently rendered as a black arrow in a gray circle. The reason seems to be that the symbol is displayed by the `.mana-q` class but the coloring is in the `.mana-untap` class.

**Comment by taw** [comment]
Fixed.
