### ISSUE TITLE
Sealed Support

### ISSUE THREAD

**Issue by taw** [taw/magic-search-engine#82]
There's an obvious feature which is currently missing, that is any concept of packs. I added partial support for it, so you can use scripts like:

`./bin/open_packs 6xM11` - open 6 packs of Magic 11
`./bin/open_packs NPH MBS SOM` - open one pack each from Scars of Mirrodin block
`./bin/open_packs --list` - list currently supported packs
`./bin/open_packs --unsupported` - list of unsupported packs

Right now it supports 117/120 sets with packs (3 to go), unfortunately missing a lot of the new ones.

Final missing sets:

- [x] Time Spiral
- [x] Planar Chaos
- [x] Future Sight
- [x] Innistrad
- [x] Dark Ascension
- [x] Vintage Masters
- [x] Shadows over Innistrad
- [x] Eldritch Moon
- [x] M19
- [x] Magic: The Gathering—Conspiracy
- [ ] Conspiracy: Take the Crown
- [ ] Unstable
- [ ] Battlebond

Other:

- [x] support sets with Planeswalker Decks (that is with cards that are part of the set, but not in boosters)
- [x] support sets with Masterpieces
- [x] `is:front` `is:back` / `is:primary` `is:secondary` queries. They differ as aftermath/flip is front secondary. DFC is back secondary. Split and normal cards are front primary.
- [x] introduce concept of `PhysicalCard`, right now it just gives left side of split card etc., won't tell you which card is foil - it will be useful for constructed decks as well
- [x] make information necessary for `is:booster` part of the indexer, and the engine
- [x] `is:booster` - card is in booster product, and not one of the extras (like planeswalker deck, or 
Firesong and Sunspeaker)
- [x] probably `CardSheet` full of `PhysicalCard` objects to encapsulate some of that stuff
- [x] command line frontend is primarily for development, not for end user, but maybe clean it up a bit
- [x] basic support for old sets (pre-Mirage), ignoring actual printing process
- [x] move foil and masterpiece logic to `CardSheet`
- [x] `CardSheet#probability(card)`
- [x] `Pack` needs same recursive structure as `CardSheet`, and `#probability(list_of_cards)`
- [x] support Dragon's Maze land slot
- [x] support Unhinged (Super Secret Tech needs special handling)
- [x] support Fate Reforged land slot
- [x] support God Packs
- [x] support whatever Time Spiral block was doing
- [x] `is:draft` support (it happens to correspond with CNS sheet)
- [x] frontend should support opening packs from multiple sets (at least three)
- [x] frontend should have nice (select2 probably) interface for selecting a set
- [x] indexer provides exact print sheet information for 8 old sets, we should use that
- [x] support sets with special sheets (first Innistrad, second Innistrad, Conspiracy draft-matters)
- [ ] support Unstable (contraptions, alt art)
- [ ] support any known variation from printed rarities, like Unstable variants (each of N-way variants appears only 1/N as often; presumably Brothers Yamazaki and other alt arts would work the same way)
- [ ] add web frontend for it, obviously (this will overlap with whichever solution we have for precons, user-uploaded decks etc.)
- [ ] maybe move more of the calculations to indexer, to make it easier for custom magic sets
- [ ] link from set page to Sealed

Nice to haves:
- [x] Dominaria apparently has "guaranteed legendary", but no separate slot. Without any tricks we get legendary in 81% of packs, and EV 1.34 legendaries per pack
- [x] old sets have special sheets with multiple rarities -  they did crazy things like two sheets with mixed rarities, basic lands on rare sheet etc. MVP is to fake it, but it would be nice to support it more accurately.
- [ ] `is:foil` / `is:nonfoil` - sort of incidental, but Sealed simulator forces getting this information, so might as well expose it. A card can match both (like M10 Lightning Bolt is available both foil and nonfoil, as is vast majority of cards), so these names are a it awkward
- [ ] to quote Maro about packs: _To match our collation, there must be at least one common of every color. Also, don't make more than five cards of the same color combination. (You can't have more than five mono-green cards or five blue-red cards.) The one exception is colorless cards if you have chosen a set that has a high as-fan of colorless cards."_

We don't have exact foil distribution information, stuff like 101st uncommon

Some sources:
* https://mtg.gamepedia.com/Booster_pack
* mtgjson has booster metadata, it seems mostly correct, but not as precise as we'd like

Probably unfixable issues:
- we don't have any collation information, I just assume you never get double of same nonfoil card
- we don't really now foil distribution, exact masterpiece chances etc.
- old sets have mixed sheets, we have information like U3 vs U2, C5 vs C4 for some of them, so we could incorporate it, but I don't think we know it for them all
- we don't have information which 101st common was half-frequency

**Comment by fenhl** [comment]
I haven't looked at your code so I apologize if you know some of this already, but here are some notes that I've made over time regarding booster pack layout:

* SOI has [about 1.125 DFCs](http://magic.wizards.com/en/articles/archive/making-magic/chasing-shadows-part-1-2016-03-14) per booster (always 1, sometimes 2).
* Unlike Wastes, old cards with multiple images like Brothers Yamazaki or High Tide (FEM) appear at the same *total* rarity as other cards, i.e. each individual version appears less often.
* ZEN had [Priceless Treasures](https://mtg.gamepedia.com/Zendikar/Priceless_Treasures), replacing the basic land and appearing roughly every 720–750 packs. Some cards appear much more frequently than others, with the rarest card being Black Lotus, though exact distribution and whether the wiki article is missing any cards is unknown.
* CN2 has a special slot for conspiracies. Other draft-matters cards appear within the normal rarity-based slots.
* Contrary to popular belief, the chance of a mythic rare in a pack is not exactly 1/8 for all sets. Instead, each individual rare [appears twice as often](http://markrosewater.tumblr.com/post/165339122268/is-the-rare-to-mythic-rare-ratio-still-the-same) as each individual mythic rare, and the total chance is derived from that.
* The ratios of rarities of foil cards [appears to be skewed towards the rare side of the distribution](https://boardgames.stackexchange.com/questions/12149/what-chance-do-i-have-of-my-foil-being-a-rare-or-mythic/39305#39305) in comparison to the well-known ratios for nonfoil cards.
* JOU packs have a chance to be [God Packs](https://magic.wizards.com/en/articles/archive/arcana/divine-gift-2014-04-28-0) (one of each of the 15 *Theros* Gods, plus a marketing card as usual), appearing roughly every 4320 packs.
* Masters sets have a foil in every pack, replacing the basic land slot.
* VMA's basic land slot is replaced with either a Power Nine card or a foil of any card in the set. From [an official article](https://www.wizards.com/Magic/Magazine/Article.aspx?x=mtg/daily/arcana/1491):
    > You will open a Power Nine card about once in 53 packs. A specific Power Nine card is about twice as rare as a specific mythic rare.

Also, I really like the idea of `is:foil` and `is:nonfoil` terms, though it should be noted that `is:nonfoil` should *not* be the same as `not:foil` since some printings (e.g. the C17 printing of Kess, Dissident Mage) are *only* available in foil and thus should be `not:nonfoil`.

**Comment by taw** [comment]
I left those complex sets for last (14 still to do).

> - [ ] SOI has about 1.125 DFCs per booster (always 1, sometimes 2).

I didn't add any sets with DFC sheet yet.

ISD/DKA has one slot for DFCs, with unknown rarity ratio.

SOI/EMN has two different DFC slots, not sure how that works.

> - [ ] Unlike Wastes, old cards with multiple images like Brothers Yamazaki or High Tide (FEM) appear at the same total rarity as other cards, i.e. each individual version appears less often.

Not currently implemented, but on todo list for Unstable etc.

> - [x]  ZEN had Priceless Treasures, replacing the basic land and appearing roughly every 720–750 packs. Some cards appear much more frequently than others, with the rarest card being Black Lotus, though exact distribution and whether the wiki article is missing any cards is unknown.

That was only in one print run, and there's no real data, so I'll just drop this completely.

> - [ ] CN2 has a special slot for conspiracies. Other draft-matters cards appear within the normal rarity-based slots.

Not implemented yet.

> - [x] Contrary to popular belief, the chance of a mythic rare in a pack is not exactly 1/8 for all sets. Instead, each individual rare appears twice as often as each individual mythic rare, and the total chance is derived from that.

Already done.

> - [x] The ratios of rarities of foil cards appears to be skewed towards the rare side of the distribution in comparison to the well-known ratios for nonfoil cards.

I googled countless claims about it, and picked some plausible numbers that do that. I'm pretty sure they're not very accurate.

There's photos of foil sheet with the usual 2 copies of each rare / 1 copy of each mythic, and total foil drop rate is printed on each pack, but rare:uncommon:common:basic ratio is unknown.

> - [ ] JOU packs have a chance to be God Packs (one of each of the 15 Theros Gods, plus a marketing card as usual), appearing roughly every 4320 packs.

Totally forgot about this one, will do.

> - [x] Masters sets have a foil in every pack, replacing the basic land slot.

Already done. Foil rarities petty much guessed.

> - [ ] VMA's basic land slot is replaced with either a Power Nine card or a foil of any card in the set. 

[OK, found a source with numbers](https://magic.wizards.com/en/articles/archive/arcana/vintage-masterss-special-rarity-2014-05-12-0)

**Comment by fenhl** [comment]
> SOI/EMN has two different DFC slots, not sure how that works.

In all packs, one of the common slots is replaced with a common or uncommon DFC. In 1 out of 8 packs, a second common slot is replaced with a rare or mythic DFC. Oh, and one thing I forgot:

* In ISD/DKA/SOI/EMN, 3 out of 4 packs replace the basic land with a checklist card. (In ORI/XLN/RIX, the checklist is in the marketing card slot.)

**Comment by taw** [comment]
I completely skipped the "checklist replaces basic" part since we don't have checklists, tokens, marketing cards etc., and it makes no difference to Limited experience anyway. Maybe something to consider much later.

**Comment by fenhl** [comment]
That makes sense, especially since I'm now finding conflicting info about whether DKA had checklists in the basic or marketing slot.

**Comment by taw** [comment]
Do you have any source on that 4320 God Pack frequency? And these are not foils, right?

I put it in, but number of unsourced assumptions I'm making, especially about foils, is really high.

**Comment by fenhl** [comment]
I wrote down [this Reddit comment](https://www.reddit.com/r/magicTCG/comments/24r0xv/how_rare_are_god_packs/cha0ei1/) as the source. It's just the word of one single person who claims to work at an LGS but I haven't found any other numbers with better sources.

**Comment by taw** [comment]
Well, exact God Pack ratio doesn't affect things much.

So the backend is quite close to done (8 sets left, of course the 8 most complex ones), leaving just two big problems:

- [ ] I'm totally guessing how foils work. I'm assuming 1/4 of packs contain a foil, it always replaces common slot, all cards from set get to be foiled (including DFCs, Timeshifted cards, basics for sets which don't otherwise put them there, conspiracies, and all the other weirdness), and some ratios between them that shouldn't be totally crazy. I don't like it, but I don't know we can do any better. Someone should at least check my assumptions and numbers if there's anything crazy there.
-  [ ] I have no idea how basics were included in old sets. From certain point of view they get own sheet, but what about before? I know for alpha [they were printed on all rarity sheets](http://www.magiclibrarities.net/forum/viewtopic.php?t=9906), but that was just a one off as far as I can tell. I assume they were by default printed on common sheet and basically worked as commons. Is that correct, or even sensible? The only set I know for which it's explicitly said its boosters didn't contain basics (but they were in fat packs etc.) was Fate Reforged.
- [ ] as intersection of these issues, foil basics.

**Comment by taw** [comment]
[Very simple Sealed is now online](http://mtg.wtf/sealed), right now it just prints unformatted list of cards, so obviously needs some sort of real UI.

There's still a bunch of backend issues (Conspiracy sets, Unstable, and Battlebond not supported; Dominaria guaranteed legend per pack not implemented; alt art not balanced properly etc.), and backend performance is a bit weak. I'd say backend is about 90% ready.

**Comment by taw** [comment]
[Now displays cards, even does foil effect](http://mtg.wtf/sealed?count=6&set=mm3).

I'm a bit lost what kind of interface would be best here. Something like MTGO Limited deck builder? Something completely different?

If anyone wants to open custom packs on loreseeker, `PackFactory` has a big switch statement which set follows which rules, so just find closest matching set and add its code there (it's not ideal place, that data sort of belongs in mtgjson or indexing time patch). Right now there are better programs for that, but hopefully we'll make this UI good.

**Comment by fenhl** [comment]
Not familiar with MTGO but maybe this could be integrated with the decklist feature somehow?

I've already implemented pack generation logic for the custom sets, will pull now and see how well it works.

**Comment by taw** [comment]
I could make Sealed pools use current decklist viewer for now. I don't think it would be that great.

As for decklist viewer, [the one saffron olive uses is so pretty](https://youtu.be/k3E9q5s32NQ?t=1m) I really want to give it a try, not sure how functional it would be really.

**Comment by taw** [comment]
So "legend" here means "legendary creature", "normal" means everything else.

Dominaria packs can have 8 kinds - 0-3 legend uncommons, times 0-1 legend rares. There are four hard constraints:

* probabilities add up to 1
* legend rares (LR) are as as frequent as normal rares (NR)
* legend uncommons (LU) are as frequent as normal uncommons (NU)
* no-legend packs (NR NU NU NU) never happen

I did the math, and implemented the simplest possible model, where packs with multiple legend uncommons never happen.  That yields just one combination of weights.

That's not ideal, as in fully random model 9/64 packs would have two legend uncommons, and 1/64 would have three. I suspect Wizards collation would try to avoid that. Anyone knows (video evidence or something) if multiple uncommon legend packs are a thing? Or if my assumptions are wrong?

**Comment by fenhl** [comment]
BFZ packs should only contain full-art basics. Similarly, OGW packs should only contain full-art Wastes.

**Comment by taw** [comment]
Right, so adding to the checklist:

- [ ] add some query for full art lands
- [ ] BFZ packs should only contain full-art basics. Similarly, OGW packs should only contain full-art Wastes.

So many things to do before even getting to the UI.

**Comment by taw** [comment]
[All these](http://mtg.wtf/card?q=t%3Abasic+t%3Aland+e%3Abfz%2Cogw+%2B%2B+-is%3Abooster) are now [excluded from Sealed](http://mtg.wtf/sealed?count%5B%5D=6&set%5B%5D=bfz&count%5B%5D=6&set%5B%5D=ogw&count%5B%5D=0&set%5B%5D=dom)

**Comment by taw** [comment]
[Might be relevant](https://twitter.com/maro254/status/1008541224276357120?s=19)

**Comment by taw** [comment]
After watching too many box opening videos, it's clear that in CNS foil draft-matters card go into draft-matters slot, not regular foil slot.

[Example](https://www.youtube.com/watch?v=nonKDTDZ--s&feature=youtu.be&t=25m30s)

**Comment by taw** [comment]
Closing as all issues moved to https://github.com/taw/magic-search-engine/issues/106
