### ISSUE TITLE
Reserved List info

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#9]
It would be useful to have a “this card is on the Reserved List” text on the card info page.

**Comment by taw** [comment]
From a quick look, the following information about cards/printings is not directly displayed.

Printing specific:

* `number` - it's somewhere on card picture for newer cards, but not for old cards (where we base in on gatherer or make it up), also there's currently no way to search it
 * `set` - we display it, but [don't link to set's page](http://mtg.wtf/set/ori) - right now they mostly contain card gallery, but we actually have some more set information we might want to display, and in such case *maybe we should link to it???*
* `release_date` - no way to infer (sometimes a bit weird with promos like FNM etc., usually just set release date)
* `watermark` - it's somewhere on card picture, but people might not know names
* `border` - easy to see on card picture
* `timeshifted` - [rulings field generally displays it](http://localhost:3000/card/pc/85), and it's easy to see on card picture. We could try to turn card names in rulings into links, but that might false positive a lot.
* `rarity` - easy to see on new cards, but not on old cards

Card specific:

* `layout` - very clear on card picture type (normal, dfc, level, split etc.)
* `reserved` - not visible
* `cmc` - usually inferable from mana cost, except for DFCs / split cards
* `colors`  - usually inferable from mana cost
* `color_identity` - usually inferable from mana cost

That's information that we actually have in processed index, [mtgjson has more](https://mtgjson.com/documentation.html) like original text/type (before Oracle)

**Comment by fenhl** [comment]
* The promos have their own `release_date` field iirc.
* Having rarity next to the list of printings would be very helpful.

**Comment by taw** [comment]
Plenty of promos have nothing printed, [like this](http://mtg.wtf/card/fnmp/145).

I've been wondering how to include rarity information on this printings - it generally needs to go with printings list, [but there are a few cards like this](http://mtg.wtf/card/kld/253).

**Comment by taw** [comment]
[I added that](http://mtg.wtf/card/un/233) and cleaned up styling a bit, but it feels rather crowded there, [especially on cards with a lot of printings](http://mtg.wtf/card?q=giant+growth).

**Comment by taw** [comment]
And now rarity display is added, and CSS tweaked to look somewhat better.

I think that's all we'll need for now.
