### ISSUE TITLE
Support official set codes in block condition

### ISSUE THREAD

**Issue by fenhl** [taw/magic-search-engine#91]
E.g. `b:TSP` instead of `b:ts`, as is already possible with `e:`.

**Comment by taw** [comment]
Definitely.

In vaguely related question, I'm wondering if we should make `b:dom` alias `e:dom`, and especially that new 3-set return to return to Ravnica thing, if it should get its block?
(neither will gets any kind of block constructed format, it's just for query consistency)

**Comment by fenhl** [comment]
People will probably be thinking of GRN/RNA/??? as a block even though those aren't officially a thing anymore, so that sounds like a good idea.

**Comment by taw** [comment]
[Works](http://mtg.wtf/card?q=b%3Alrw) and [works](http://mtg.wtf/card?q=b%3Adom)

**Comment by taw** [comment]
Never mind, I misspelled one code :-p

**Comment by taw** [comment]
Now it properly works.
