### ISSUE TITLE
Dominaria oracle text update: "to your mana pool" is omitted

### ISSUE THREAD

**Issue by bernhardschuller** [taw/magic-search-engine#95]
Due to the oracle text update from Dominaria, where "to your mana pool" is omitted after "Add {x}", it will be hard to search for cards that add mana without specifying the mana identity. In this case, it might help to support a syntax like "add {?}".

**Comment by fenhl** [comment]
Would be nice to have, perhaps using the same `{M}{N}{O}` syntax already used for mana costs.

As a workaround, you can use regex to get this today: [`o:/add \{.\}/`](https://mtg.wtf/card?q=o%3A%2Fadd+%5C%7B.%5C%7D%2F)

**Comment by taw** [comment]
I think [`o:"add {"`](http://mtg.wtf/card?q=o%3A%22add+%7B%22) should get you all cards that add any amount of mana.

The only counterexample I can think of is cards which add mana due to their type (like shocklands) without explicit text.

**Comment by fenhl** [comment]
There's a few others, like cards that produce mana of any color (e.g. [Black Lotus](https://mtg.wtf/card/vma/4)) or mana abilities with weird templating like [Doubling Cube](https://mtg.wtf/card/10e/321).

**Comment by taw** [comment]
Right, so what could we do that would improve search experience here?

I don't think `is:mana` would be supper useful, especially since then we run into issue where to draw the line, with shocklands, fetchlands, Doubling Cube, [Arbor Elf](http://mtg.wtf/card/m13/160/Arbor-Elf) etc.

**Comment by bernhardschuller** [comment]
Further examples where "to your mana pool" is omitted include [Mana Drain](http://mtg.wtf/card/ima/65/Mana-Drain) and [Nykthos, Shrine to Nyx](http://mtg.wtf/card/ths/223/Nykthos-Shrine-to-Nyx) with the wording "an amount".

To preserve the search experience as it was before the oracle text update, a regex could be provided that includes i.e.
"add {"
"add (one|two|three|...)"
"add an amount of {"
"add an amount of mana"
"add X mana"

This would also leave out Doubling Cube and Arbor Elf, which weren't included in "to your mana pool" searches before.

**Comment by taw** [comment]
Would searching for o:/\badd\b/ match exactly what you want?

**Comment by bernhardschuller** [comment]
Right! I guess "add" is strictly for mana. This should work.
Thank you!
